# -*- coding: utf-8 -*-
"""Replace templated Section 33 Q&A with specific interview content."""

def qa(n, q, a, e):
    return (
        f'<div class="callout"><p><strong>Q{n}:</strong> {q}</p>\n'
        f'<p><strong>Answer:</strong> {a}</p>\n'
        f'<p><em>Interviewer expects:</em> {e}</p></div>\n\n'
    )

# --- Cucumber Intermediate Q31-Q65 ---
cuc_int = [
("What are Cucumber hooks?", "Hooks are methods with @Before, @After, @BeforeStep, @AfterStep annotations. @Before runs before each scenario; @After runs after regardless of pass/fail. Use for WebDriver init/quit, screenshot capture, test data setup. Tagged hooks @Before(\"@ui\") run only for matching scenarios. Hooks live in glue package alongside step definitions.", "Driver lifecycle in hooks, not in every step definition."),
("How do you use tagged hooks?", "@Before(\"@smoke and not @api\") public void beforeSmoke(Scenario s) { }. Tag expression syntax same as runner tags. Multiple tags supported. Use for browser setup per tag, API auth for @api scenarios only. Avoid too many tagged hooks — increases complexity. Document hook-tag mapping in framework README.", "Selective setup/teardown based on scenario tags."),
("What are Data Tables in Cucumber?", "Data Tables pass structured tabular data to step definitions. In Gherkin: | name | email | followed by rows. Java: DataTable parameter, or List<Map<String,String>> for header-keyed rows. Use for form filling, expected result comparison, API payload construction. DataTable.asMaps() converts to list of maps.", "List<Map> conversion and form-filling use case."),
("How do you convert Data Tables to POJOs?", "Use @DataTableType annotation on a method: @DataTableType def User user(Map<String,String> row) { return new User(row.get(\"name\")); }. Step def accepts List<User>. Cleaner than manual map parsing. Register in glue package. Cucumber 7+ supports default data table converters.", "Custom type registration for type-safe tables."),
("What is Scenario Context in hooks?", "Scenario scenario parameter in @Before/@After provides: getName(), getId(), getSourceTagNames(), getLine(), isFailed(). Use getName() for screenshot filenames. getSourceTagNames() for conditional logic. Attach text/screenshot: scenario.attach(bytes, \"image/png\", \"Screenshot\"). Available in Cucumber 7+.", "Scenario metadata for reporting and debugging."),
("What are Doc Strings in Cucumber?", "Triple-quoted text block in Gherkin passed as String to step definition. Used for JSON payloads, long text input, expected content. Example: When I submit JSON: \"\"\"{\"name\":\"John\"}\"\"\". Step: @When(\"I submit JSON:\") public void submit(String json). Alternative to inline strings for multiline content.", "Multiline string parameter for API payloads."),
("How do you implement custom Cucumber parameters?", "Custom ParameterType: @ParameterType(\"(\\\\d+)px\") public int pixel(String px) { return Integer.parseInt(px.replace(\"px\",\"\")); }. Use in step: @Then(\"width should be {pixel}\"). Transforms matched text to custom type. Register in glue package. Reduces regex complexity in step definitions.", "ParameterType annotation for domain-specific types."),
("What is Cucumber timeline report?", "plugin = \"timeline:target/timeline\" generates HTML timeline showing scenario execution chronologically. Visualizes parallel execution, identifies bottlenecks. Each thread shown as separate row. Useful for optimizing parallel Cucumber runs. Open target/timeline/index.html after execution.", "Performance analysis of parallel scenario execution."),
("What is rerun plugin in Cucumber?", "plugin = \"rerun:target/rerun.txt\" writes failed scenario paths to file. Re-run only failures: mvn test -Dcucumber.features=@target/rerun.txt. Speeds up CI failure feedback loop. Combine with retry in hooks for flaky scenarios. Standard practice in mature CI pipelines.", "Failure-only re-execution strategy."),
("How do you organize feature files?", "One feature per application module: login.feature, checkout.feature. Group related scenarios under one Feature keyword. Place in src/test/resources/features/ mirroring app structure. Avoid mega feature files with 50+ scenarios. Use subdirectories: features/api/, features/ui/. Consistent naming: verb-noun.feature.", "Feature file organization mirroring application modules."),
("How do you reuse steps across features?", "Same step text in multiple features maps to one step definition. Design reusable, generic steps: \"I am logged in as {string}\" not \"I login with admin credentials\". Shared step definition classes in common glue package. Avoid duplicate step definitions with slightly different wording.", "Reusable generic step design philosophy."),
("What is declarative vs imperative Gherkin?", "Declarative: \"Given I am logged in\" (what, not how). Imperative: \"Given I click login button and enter user and pass\" (how). Declarative is BDD best practice — readable by business. Implementation details hidden in step definitions. Imperative Gherkin becomes unmaintainable as UI changes.", "Strong preference for declarative style with examples."),
("How do you handle waits in Cucumber steps?", "Use explicit WebDriverWait inside step definitions or Page Objects — never Thread.sleep. Wrap in page object methods: wait.until(ExpectedConditions.visibilityOfElementLocated(locator)). Keep Gherkin free of wait language. Centralize timeout values in config.properties. Log wait timeouts for debugging slow pages.", "Explicit waits in page objects, not Gherkin or sleep."),
("How do you take screenshots in Cucumber?", "@After hook: if (scenario.isFailed()) { byte[] screenshot = ((TakesScreenshot)driver).getScreenshotAs(OutputType.BYTES); scenario.attach(screenshot, \"image/png\", scenario.getName()); }. Works with Allure and Cucumber native reports. Also capture on @AfterStep for step-level debugging.", "Hook-based screenshot on failure pattern."),
("What is Cucumber strict mode?", "In older versions, strict=true failed suite on pending/undefined steps. Cucumber 7 treats undefined steps as errors by default. Use dryRun=true during development to catch undefined steps. In CI, any undefined step should fail the build immediately.", "Zero tolerance for undefined steps in CI."),
("How do you test negative scenarios in Cucumber?", "Write explicit negative scenarios: Scenario: Login with invalid password. Then step verifies error message. Use Examples table for multiple invalid inputs. Tag @negative for separate CI execution. Don't mix positive and negative in same scenario — one behavior per scenario.", "Dedicated negative scenarios with clear Then assertions."),
("What is the Rule keyword in Gherkin?", "Rule groups scenarios under a business rule. Feature: Password Policy / Rule: Minimum 8 characters / Scenario: Valid password. Improves organization in complex features. Optional — not all teams use it. Supported in Gherkin 6+. Scenarios under a Rule inherit its context.", "Business rule grouping in feature files."),
("How do you run Cucumber from Maven with tags?", "mvn test -Dcucumber.filter.tags=\"@smoke and not @wip\". Override features: -Dcucumber.features=path/to/feature. Override glue: -Dcucumber.glue=com.steps. Configure defaults in @CucumberOptions on runner class. Jenkins parameterizes tag expression per build type.", "Maven command-line tag filtering for CI."),
("What is monochrome in @CucumberOptions?", "monochrome=true removes ANSI color codes from console output. Useful for CI logs that don't support colors. Output is plain text — easier to parse in Jenkins console. Keep pretty plugin for local development with colors. Set monochrome=true in CI runner configuration.", "CI-friendly console output configuration."),
("How do you handle multiple environments in Cucumber?", "ConfigReader loads properties based on -Denv system property. @Before hook reads env and sets base URL. Environment-specific feature files rarely needed — same features, different config. Jenkins injects env-specific credentials. Never hardcode URLs in feature files or step definitions.", "Environment config externalization pattern."),
("What is snippet generation?", "When Cucumber finds undefined steps, console prints suggested step definition skeletons. snippets=CamelCase or PASCALCASE controls method naming. Use during development: run with dryRun=false, copy snippets, implement methods. Speeds up step definition creation.", "Development workflow using snippet output."),
("How do you validate API responses in Cucumber steps?", "Use REST Assured in @Then steps: response.then().statusCode(200).body(\"name\", equalTo(\"John\")). Store Response in scenario-scoped variable via PicoContainer or instance field. Separate API steps from UI steps using @api tag. API steps should not reference WebDriver.", "REST Assured integration in Then steps."),
("What is conditional execution in Cucumber?", "Tagged hooks for conditional setup. ITestContext or static flags for runtime decisions. Skip scenario: throw new PendingException(\"Feature not ready\") — marks pending/skipped. @Before hook checks environment availability and throws exception to skip. Prefer tag-based filtering over runtime skipping.", "Tag-based filtering preferred over runtime skip."),
("How do you share state between step definitions?", "PicoContainer DI (cucumber-picocontainer dependency): shared classes auto-injected into step def constructors. Instance fields in same step def class for multi-step scenarios. Scenario Context via custom World object. Never use static fields for WebDriver in parallel — use ThreadLocal.", "PicoContainer for shared state between steps."),
("What is Cucumber 7 migration from older versions?", "Package change: io.cucumber replaces cucumber.api. Update imports in step defs and hooks. junit-vintage removed — use junit-platform or TestNG. Message protocol replaces old formatter API. Update pom.xml: io.cucumber:cucumber-java:7.x, cucumber-testng:7.x. Run dryRun to verify all steps still match.", "io.cucumber package migration knowledge."),
("How do you integrate Cucumber with Spring?", "cucumber-spring dependency. @CucumberContextConfiguration on Spring config class. @Autowired beans into step definitions. Spring manages test context lifecycle. Useful for integration tests needing Spring beans, DB repositories, or service layer. @Before hook can @Autowired WebDriver bean.", "Spring context in step definitions for integration tests."),
("What is feature-level vs scenario-level tags?", "Feature-level tag applies to all scenarios in feature unless scenario has overriding tag. @smoke on Feature tags every scenario. Scenario-level tag adds to feature tags. Tag inheritance: scenario tags = feature tags + own tags. Use feature tags for module-wide categorization.", "Tag inheritance from feature to scenarios."),
("How do you name scenarios properly?", "Name describes behavior and expected outcome: \"Successful login with valid credentials\" not \"Test 1\". Include business context. Avoid technical terms in names. Scenario Outline: name describes pattern: \"Login fails with <reason>\". Consistent naming helps report readability and failure triage.", "Business-readable scenario naming convention."),
("What is the pickle runner in Cucumber?", "Pickle is internal Cucumber representation of executable scenario (compiled from AST). Each Example row creates separate Pickle. Understanding Pickles helps debug parallel execution and report mapping. Not directly exposed to users but referenced in advanced parallel configuration.", "Internal scenario representation awareness."),
("How do you handle authentication in Cucumber?", "Fast approach: API login in @Before hook, inject token/cookie into browser. UI login as dedicated scenario for login feature only. Store auth state in PicoContainer shared context. @Before(\"@authenticated\") hook performs login. @After hook clears session. Never login via UI in every scenario.", "API-based auth setup in hooks for speed."),
("What is cucumber-junit-platform-engine?", "Cucumber 7 JUnit 5 integration via junit-platform-engine. Alternative to AbstractTestNGCucumberTests. Use @Suite with @SelectClasspathResource for JUnit 5. Better IDE integration with JUnit 5. TestNG still preferred in enterprise Selenium projects for parallel and listener features.", "Awareness of JUnit 5 vs TestNG runner options."),
("How do you lint Gherkin files?", "Use gherkin-lint npm tool or review checklist: max 10 steps per scenario, no And as first step, declarative language, consistent Given-When-Then. CI can run gherkin-lint as pre-commit hook. Prevents feature file quality degradation over time.", "Gherkin quality enforcement in CI."),
("What is the difference between Cucumber and SpecFlow?", "Cucumber-JVM for Java/Kotlin. SpecFlow for .NET/C#. Both use Gherkin syntax. SpecFlow integrates with Visual Studio and Reqnroll (successor). Cucumber has larger Java community. Same BDD principles apply. Choose based on technology stack.", "Tool selection based on tech stack."),
("How do you handle file upload in Cucumber?", "Step definition: driver.findElement(By.id(\"file\")).sendKeys(absoluteFilePath). File must exist on machine running test. In CI, store test files in src/test/resources/testdata/. For remote grid, use LocalFileDetector. Never interact with OS file dialog — sendKeys to hidden input.", "sendKeys file upload pattern, not OS dialog."),
("What is scenario-level timeout in Cucumber?", "Configure via TestNG @Test(timeOut) on runner or custom @Before hook with ExecutorService and Future.get(timeout). Cucumber itself has no native scenario timeout. Wrap scenario execution or set TestNG timeout on runner class methods. Log timeout with scenario name for debugging.", "Timeout via TestNG integration or custom hook."),
]

cuc_adv = [
("How do you run Cucumber scenarios in parallel?", "cucumber.execution.parallel.enabled=true in junit-platform.properties or @DataProvider parallel with AbstractTestNGCucumberTests. Set parallel config: cucumber.execution.parallel.config.strategy=dynamic, fixed, or custom. Each scenario runs in separate thread. Requires ThreadLocal WebDriver and independent test data. Start with 2-4 threads, scale based on CI capacity.", "Parallel config properties and thread safety requirements."),
("What is PicoContainer in Cucumber?", "cucumber-picocontainer dependency enables constructor injection in step definitions. Shared objects (DriverFactory, ApiClient) injected automatically. Scenario-scoped lifecycle — new instances per scenario. Constructor: public LoginSteps(WebDriver driver, LoginPage page). Eliminates static state. Required for parallel Cucumber execution.", "Constructor injection pattern with PicoContainer."),
("How do you design Cucumber framework architecture?", "Layers: Features → Step Definitions → Page Objects/Services → Utilities. Runner classes per suite (smoke, regression). Hooks class for driver lifecycle. PicoContainer for DI. ConfigReader for environment. Separate glue packages: steps, hooks, pages, utils. One runner per tag group in CI.", "Layered architecture diagram explanation."),
("How do you test REST APIs with Cucumber?", "REST Assured in step definitions. Given sets base URI and auth. When sends request. Then validates status and body. Service Object pattern: UserApiService wraps REST Assured calls. Tag @api for API-only scenarios. No WebDriver in API steps. Store Response in shared context.", "Complete API testing layer in Cucumber framework."),
("How do you implement Cucumber with Selenium Grid?", "@Before hook creates RemoteWebDriver with grid URL and capabilities. Pass -Dgrid.url=http://hub:4444. Parallel scenarios connect to different grid nodes. Docker Compose for local grid setup. Cloud providers (BrowserStack) as managed grid. Quit driver in @After hook to release node.", "RemoteWebDriver setup in hooks for grid execution."),
("What is Cucumber message protocol?", "Standardized event format (NDJSON) for Cucumber execution. plugin = \"message:target/messages.ndjson\". Consumed by Allure, custom report generators. Replaces legacy JSON formatter internals. Enables tool-agnostic report processing. Foundation for Cucumber Reports cloud service.", "Modern reporting protocol awareness."),
("How do you publish Cucumber reports?", "publish=true in @CucumberOptions uploads to Cucumber Reports cloud. Requires Cucumber CI token. Self-hosted: generate json plugin, process with Allure or Jenkins Cucumber Report plugin. Attach html report to Jira bugs. Archive reports as CI build artifacts with retention policy.", "Report publishing in enterprise CI pipeline."),
("How do you handle dynamic data in Cucumber?", "Generate at runtime in @Before hook: String email = \"user_\" + UUID.randomUUID() + \"@test.com\". Faker library for realistic data. API creates test data, UI verifies. Store generated values in PicoContainer context for later steps. Cleanup in @After hook via API or DB.", "Runtime data generation with cleanup strategy."),
("What is shared WebDriver anti-pattern?", "Static WebDriver field shared across scenarios causes failures in parallel execution. Thread A navigates while Thread B quits driver. Fix: ThreadLocal in DriverFactory, inject via PicoContainer. One driver per scenario thread. Never pass driver as static. Code review for static driver references.", "Identify and fix shared driver anti-pattern."),
("How do you version Cucumber dependencies?", "Pin io.cucumber version in pom.xml properties: <cucumber.version>7.18.0</cucumber.version>. Align cucumber-java, cucumber-testng, cucumber-picocontainer to same version. Test with dryRun after upgrades. Watch GitHub releases for breaking changes. Automated Dependabot PRs with smoke suite validation.", "Dependency version alignment strategy."),
("How do you test microservices with Cucumber?", "Each service has feature files for its API endpoints. Shared authentication steps. Contract tests verify service interfaces. Orchestration scenarios test cross-service flows. Tag by service: @user-service, @order-service. Independent execution per service in CI. Mock external dependencies with WireMock.", "Microservice BDD organization strategy."),
("What is Cucumber anti-pattern: long scenarios?", "Scenarios with 20+ steps are unmaintainable. Split into focused scenarios with Background for shared setup. Each scenario tests one behavior. Long scenarios indicate missing abstraction in step definitions. Review feature files in PR — reject scenarios exceeding 10 steps.", "Scenario length governance in code review."),
("How do you implement custom Cucumber plugin?", "Implement ConcurrentEventListener or EventListener. Register via @CucumberOptions plugin class. Handle TestCaseStarted, TestCaseFinished events. Generate custom metrics, send to monitoring system. Advanced use case for enterprise observability integration.", "Custom event listener plugin development."),
("What is dependency injection beyond PicoContainer?", "Spring DI with cucumber-spring for Spring Boot apps. Guice with cucumber-guice. Manual DI via constructor in simple frameworks. PicoContainer is lightest for Selenium projects. Choose based on application architecture — match app's DI framework.", "DI option selection rationale."),
("How do you handle iFrames in Cucumber?", "Page Object method: driver.switchTo().frame(locator), interact, switchTo().defaultContent(). Step definition calls page object — no frame logic in Gherkin. Handle nested frames with switchTo().parentFrame(). Always return to default content in finally block to prevent context leaks.", "Frame handling encapsulated in page objects."),
("What is Cucumber filter tags property?", "System property cucumber.filter.tags overrides @CucumberOptions tags at runtime. Jenkins: mvn test -Dcucumber.filter.tags=\"@regression and @ui\". Enables same runner for different CI jobs. Takes precedence over annotation. Supports full tag expression syntax.", "Runtime tag override for CI parameterization."),
("How do you integrate Allure with Cucumber 7?", "Dependency: io.qameta.allure:allure-cucumber7-jvm. Auto-attaches scenario results. @Step annotation on step definition methods for detailed steps in report. scenario.attach() for screenshots. Generate: allure serve target/allure-results. Rich timeline, categories, severity.", "Allure + Cucumber 7 integration setup."),
("What is testable Gherkin review checklist?", "Is it declarative? One behavior per scenario? Readable by product owner? No technical locators? Reusable steps? Proper tags? Examples cover edge cases? Background minimal? Follows team style guide? Review in Three Amigos session before automation.", "Quality checklist for feature file review."),
("How do you handle OAuth in Cucumber?", "API step obtains token via client credentials or password grant. Store token in scenario context. UI step injects cookie/localStorage. Alternatively automate OAuth UI flow in dedicated @oauth tagged scenarios. Use test OAuth server or mock authorization server. Never store real OAuth secrets in feature files.", "OAuth automation strategy for test environments."),
("What is Cucumber execution dry-run vs runtime?", "dryRun=true: validates step defs, no browser/API calls. Runtime: full execution with all hooks and steps. CI pipeline: dryRun in PR validation (fast), full run on merge. Local: dryRun when adding new scenarios, runtime for development. Combine: dryRun catches missing steps before wasting CI time.", "Two-phase validation in CI pipeline."),
("How do you migrate from Cucumber 4 to 7?", "Update pom.xml dependencies to io.cucumber 7.x. Replace cucumber.api imports with io.cucumber.java.en. Update hook imports: io.cucumber.java.Before. Replace AbstractTestNGCucumberTests import. Test EventListener API if custom plugins. Run full suite with dryRun first, then runtime.", "Step-by-step migration experience."),
("What is World object in Cucumber?", "Shared context object holding scenario state: tokens, created IDs, WebDriver reference. Instantiate via PicoContainer or @Before hook. Step definitions access World's fields. Cleaner than static variables. Pattern: public class TestContext { public String orderId; public WebDriver driver; }.", "World/Context object pattern for scenario state."),
("How do you optimize slow Cucumber suites?", "Profile with timeline report. Identify slowest scenarios. Replace UI setup with API setup. Reduce unnecessary Background steps. Parallel execution. Headless browser mode. Skip non-critical scenarios in smoke. Cache authentication tokens. Target: smoke under 10 minutes, regression under 1 hour.", "Data-driven suite optimization approach."),
("What is BDD framework governance?", "Gherkin style guide document. Feature file templates. Step definition naming conventions. PR review checklist for .feature files. Regular Three Amigos sessions. Archive obsolete scenarios. Tag strategy document. Onboarding guide for new team members. Quarterly feature file audit.", "Framework governance for team scale."),
("How do you test GraphQL with Cucumber?", "HTTP client or REST Assured with GraphQL query in request body. Step: When I query GraphQL with query \"{ users { id name } }\". Then validate JSON response path. Store queries in external .graphql files for complex queries. Tag @graphql for separate execution.", "GraphQL testing approach in BDD framework."),
("What is Cucumber compatibility with JUnit 5?", "cucumber-junit-platform-engine for native JUnit 5. @Suite + @IncludeEngines(\"cucumber\"). Parallel via JUnit 5 parallel config. TestNG still more common in Selenium for ITestListener and XML suites. JUnit 5 better for Spring Boot integration test projects.", "JUnit 5 vs TestNG runner selection criteria."),
("How do you handle database in Cucumber steps?", "JDBC utility in @Then steps for validation. @Before seed data, @After cleanup. DatabaseHelper class with query/execute methods. Never embed SQL in Gherkin — keep in Java. Use test database, never production. Connection pool for parallel: HikariCP with thread-safe access.", "DB validation pattern with cleanup in hooks."),
("What is event-driven Cucumber reporting?", "ConcurrentEventListener receives events during execution. Send to Kafka, Elasticsearch, or custom dashboard in real-time. Enables live test execution monitoring in CI. Advanced pattern for large organizations with centralized quality dashboards.", "Real-time reporting architecture awareness."),
("How do you cross-validate Cucumber and TestNG reports?", "Cucumber json report + TestNG testng-results.xml should show same pass/fail counts. Discrepancies indicate runner configuration issues. Unified dashboard merges both. TestNG listener captures Cucumber scenario results. Align naming: scenario name visible in both reports.", "Report reconciliation in hybrid framework."),
("What is your Cucumber framework maintenance plan?", "Weekly: review failed scenarios, update selectors. Monthly: dependency updates, remove obsolete scenarios. Quarterly: refactor duplicated steps, optimize slow scenarios. Version control feature files with same rigor as code. Metrics: scenario count, pass rate, avg duration, undefined step count.", "Long-term BDD framework ownership plan."),
("How do you train team on Cucumber/BDD?", "Week 1: BDD concepts, Gherkin syntax. Week 2: Step definitions, hooks. Week 3: Page Objects, framework structure. Week 4: Hands-on — write feature file + automate. Pair programming for first scenarios. Gherkin style guide as reference. Three Amigos workshop for PO + Dev + QA.", "Structured team onboarding plan for BDD."),
("What is Cucumber in CI/CD quality gate?", "Fail build if: any scenario fails, undefined steps exist, pass rate below threshold. Smoke tag on every PR. Full regression on merge to main. Nightly scheduled run. Publish reports as artifacts. Slack notification on failure. Track pass rate trend over 30 days.", "CI quality gate configuration for Cucumber suites."),
("How do you handle WebDriverManager in Cucumber?", "WebDriverManager.chromedriver().setup() in @Before hook or DriverFactory. Auto-downloads matching driver version. Eliminates manual driver management. Works with local and CI. Configure in DriverFactory: WebDriverManager.firefoxdriver().setup(). Keep version pinned for CI stability.", "WebDriverManager integration in framework."),
("What is the future of Cucumber testing?", "Cucumber Open Source continues with message protocol, JUnit 5 integration. AI-assisted Gherkin generation from requirements. Self-healing step definitions. Cloud-native test execution. Integration with observability platforms. BDD remains relevant for communication — tool evolves around it.", "Forward-looking perspective on BDD tooling."),
("How do you lead BDD adoption in a team?", "Start with pilot feature, demonstrate value. Three Amigos workshops. Pair PO with QA on Gherkin writing. Show living documentation to stakeholders. Measure: reduced requirement defects, faster onboarding. Don't force 100% coverage — start with critical user journeys. Celebrate early wins.", "Change management skills for BDD adoption."),
]

# Build replacement block
block = '<h4>Intermediate (35)</h4>\n\n'
for i, (q, a, e) in enumerate(cuc_int, 31):
    block += qa(i, q, a, e)
block += '<h4>Advanced (35)</h4>\n\n'
for i, (q, a, e) in enumerate(cuc_adv, 66):
    block += qa(i, q, a, e)

# BDD 50 questions
bdd = [
("What is the Three Amigos ceremony?", "Meeting with Business (PO/BA), Developer, and Tester before implementing a user story. Review acceptance criteria, write Gherkin scenarios together, identify edge cases. Ensures shared understanding before coding starts. Typically 30-45 minutes per story. Output: approved feature file scenarios ready for automation.", "Collaboration process experience, not just definition."),
("What is living documentation?", "Feature files that serve as always-current documentation because they execute as tests. When code changes, scenarios fail until updated — keeping docs synced with behavior. Readable by non-technical stakeholders. Stored in git alongside code. More reliable than wiki pages that become stale.", "Docs that self-validate through test execution."),
("What is ubiquitous language?", "Shared vocabulary between business and tech teams used consistently in feature files, code, and conversations. If business says \"order\", Gherkin says \"order\", code uses Order class. Reduces miscommunication. Established during Three Amigos sessions. Documented in team glossary.", "Shared domain language across team boundaries."),
("What is Example Mapping?", "Workshop technique: index cards for Rules (yellow), Examples (green), Questions (red), Stories (blue). Map business rules to concrete examples before writing Gherkin. Identifies gaps and ambiguities early. 30-minute timeboxed session. Output feeds directly into feature file scenarios.", "Practical workshop facilitation experience."),
("What is Specification by Example?", "Define requirements as concrete examples rather than abstract statements. \"Login fails with wrong password\" not \"system validates credentials\". Examples become automated tests. Core BDD principle predating Cucumber. Ensures testable, unambiguous requirements.", "Concrete examples over vague requirements."),
("What is the difference between BDD and TDD?", "TDD: developer writes unit tests first, then code (Red-Green-Refactor). BDD: team defines behavior examples first using Gherkin, then automates. TDD focuses on code correctness at unit level. BDD focuses on behavior at feature level. Complementary — use both. BDD drives acceptance; TDD drives design.", "Complementary, not competing approaches."),
("What are common BDD anti-patterns?", "Imperative Gherkin (click, type, verify). Testing through UI only. No Three Amigos — QA writes Gherkin alone. Scenarios too long (20+ steps). Technical jargon in features. Treating BDD as just a testing tool. Duplicate step definitions. No living documentation mindset.", "Recognize and prevent anti-patterns from experience."),
("What is imperative vs declarative Gherkin?", "Imperative: \"When I click login and enter user and pass and click submit\". Declarative: \"When I login as admin\". Declarative hides implementation, survives UI changes. BDD best practice is declarative. Implementation details belong in step definitions and page objects only.", "Strong declarative preference with before/after examples."),
("What is the role of Product Owner in BDD?", "PO participates in Three Amigos, validates Gherkin scenarios match business intent, prioritizes scenarios for automation, reviews living documentation. PO doesn't write step definitions but approves feature file content. PO ensures scenarios cover acceptance criteria completely.", "PO as active BDD participant, not passive recipient."),
("How do you write good Gherkin scenarios?", "One behavior per scenario. Declarative language. Clear Given-When-Then. Meaningful scenario name. Relevant tags. Minimal Background. Use Scenario Outline for data variations. Max 10 steps. Readable by PO without technical explanation. Review in Three Amigos before automation.", "Quality Gherkin writing with team review process."),
("What is outside-in development?", "Start with user-facing acceptance scenarios (outside), then implement code (in) to make them pass. BDD enables this: write failing scenario first, implement feature, scenario passes. Ensures development driven by user value. Contrasts with inside-out (database up) approach.", "User-value-driven development approach."),
("How do you measure BDD ROI?", "Track: requirement defect reduction, time to onboard new team members (read feature files), regression test creation speed, PO confidence in releases. Compare defect escape rate before/after BDD. Measure scenario coverage vs acceptance criteria coverage. Qualitative: improved team communication.", "Quantifiable and qualitative BDD success metrics."),
("What is a Gherkin style guide?", "Team document defining: max steps per scenario, declarative language rules, naming conventions, tag strategy, when to use Background vs Given, Scenario Outline guidelines. Enforced in PR review. Example: \"Never use UI element names in Gherkin\". Prevents feature file quality drift.", "Team standards enforcement for Gherkin quality."),
("How do you handle BDD in Agile sprints?", "Three Amigos during refinement (sprint N-1). Scenarios written before development (sprint N). Automation during or after development. Demo using Gherkin scenarios in sprint review. Scenarios map to acceptance criteria on story. BDD scenarios are part of Definition of Done.", "BDD integrated into sprint ceremonies."),
("What is acceptance criteria vs BDD scenarios?", "Acceptance criteria: conditions on user story (often bullet points). BDD scenarios: executable Given-When-Then versions of those criteria. Each criterion maps to one or more scenarios. Scenarios are testable; criteria may be vague. Three Amigos converts criteria to scenarios.", "Criteria-to-scenario mapping process."),
("What is executable specification?", "Gherkin scenario that runs as automated test AND serves as specification. Single source of truth for behavior. Eliminates separate test plan documents. When application changes, failing scenario signals spec needs update. Core value proposition of BDD with Cucumber.", "Single artifact for spec and test."),
("What is domain-driven testing?", "Test organization mirrors business domain, not technical architecture. Feature files named by business capability: checkout.feature not test_page_3.feature. Steps use business language. Aligns testing with how stakeholders think about the product. Supports ubiquitous language principle.", "Business-domain-aligned test organization."),
("How do you do BDD for API testing?", "Feature files describe API behavior: \"When I create user with valid data Then response status is 201\". Same Gherkin principles — declarative, business-focused. Tag @api. No UI steps mixed in. API scenarios often faster and more stable than UI scenarios. Good BDD entry point for microservices.", "BDD beyond UI — API feature file examples."),
("How do you scale BDD across multiple teams?", "Shared Gherkin style guide and step library. Common glue package for reusable steps. Feature file ownership per team/product area. Central framework team maintains infrastructure. Regular cross-team sync on shared steps. Avoid duplicate step definitions across teams.", "Multi-team BDD governance experience."),
("What is BDD maturity model?", "Level 1: QA writes Gherkin alone. Level 2: Three Amigos for some stories. Level 3: All stories have Gherkin before development. Level 4: Living documentation trusted by stakeholders. Level 5: BDD drives product discovery. Assess team level and plan progression.", "Honest team maturity assessment and improvement plan."),
("What is feature file ownership?", "Each feature file owned by a team or feature area. PO approves content, QA automates, Dev reviews step definitions. Git CODEOWNERS for feature files. Changes require PO review. Prevents unauthorized scenario modifications. Clear ownership reduces orphaned scenarios.", "Ownership model preventing feature file chaos."),
("How do you handle legacy systems with BDD?", "Start with critical user journeys, not full coverage. Wrap legacy UI with page objects. Write scenarios for new features in BDD. Gradually add scenarios for legacy as areas are modified. Don't attempt big-bang BDD migration. Focus on highest business value flows first.", "Incremental BDD adoption for legacy systems."),
("What is incremental BDD adoption?", "Phase 1: Pilot one feature with Three Amigos. Phase 2: All new features use BDD. Phase 3: Retrofit critical existing flows. Phase 4: Full regression in BDD. Don't force entire team at once. Demonstrate value with pilot success. Provide training at each phase.", "Phased adoption plan with pilot-first approach."),
("What is BDD in regulated industries?", "Feature files serve as compliance evidence — auditable test records. Scenarios must trace to requirements (requirement ID in tag). Strict change control on feature files. Execution reports archived for audit. Gherkin provides readable evidence for non-technical auditors.", "Compliance and audit trail awareness."),
("What is non-automation BDD?", "Gherkin scenarios executed manually during exploratory or sprint testing. Not all scenarios need automation. Manual BDD scenarios guide structured exploratory testing. Automate high-value, repeatable scenarios. Manual for UX, visual, one-time investigations.", "BDD value beyond automation."),
("What is exploratory BDD?", "Use Gherkin structure to guide exploratory testing sessions. Tester deviates from script but documents findings in scenario format. Combines structured and exploratory approaches. Useful for new features where scenarios aren't fully known upfront.", "Flexible BDD application for discovery testing."),
("How do you facilitate a Three Amigos session?", "Timebox 30-45 min. Review story and acceptance criteria. Write Gherkin scenarios collaboratively. Identify questions (red cards in Example Mapping). Agree on scope. Assign automation owner. Document decisions. Don't let it become a design meeting — focus on behavior examples.", "Facilitation skills and session structure."),
("What is behavior coverage?", "Percentage of acceptance criteria covered by at least one Gherkin scenario. Unlike code coverage, measures business behavior testing completeness. Track: criteria count vs scenario count. Gap analysis: criteria without scenarios. Target: 100% criteria coverage for P1 features.", "Business behavior coverage metric."),
("How do you audit feature files?", "Quarterly review: obsolete scenarios, duplicated coverage, imperative Gherkin, missing tags, overly long scenarios. Metrics: total scenarios, pass rate, avg steps per scenario. Archive unused features. Update scenarios matching changed behavior. Audit report shared with team.", "Proactive feature file maintenance process."),
("What is BDD vs traditional test planning?", "Traditional: separate test plan document, often stale. BDD: scenarios in feature files, always current. Traditional: QA plans alone. BDD: whole team contributes. Traditional: traceability matrix. BDD: scenarios directly map to acceptance criteria. BDD eliminates duplicate documentation.", "Documentation efficiency comparison."),
("How does BDD support shift-left testing?", "Testing begins during requirements refinement with Three Amigos. Scenarios written before code — defects found in discussion, not production. Acceptance criteria validated early. Automation starts during development, not after. Reduces cost of defect fix by catching issues earlier.", "Shift-left concrete practices in BDD context."),
("What is BDD and DevOps integration?", "Feature files triggered in CI/CD pipeline. Tag-based suite selection per deployment stage. Smoke scenarios gate deployments. BDD reports published as deployment artifacts. Failed scenarios block promotion. Living documentation accessible to ops team for behavior reference.", "BDD as CI/CD quality gate."),
("What is conjunction in Gherkin (And/But)?", "And continues previous step type — And after Given is still precondition. But implies contrast/exception. Improves readability over repeating Given/When/Then. Rule: first step sets type, subsequent And/But follow. Never start scenario with And.", "Correct And/But usage rules."),
("How do you avoid technical jargon in Gherkin?", "Use business terms: \"submit order\" not \"click #submit-btn\". \"See confirmation\" not \"verify element .success-msg displayed\". If PO can't understand scenario, rewrite it. Technical details belong in step definitions. Review with PO in Three Amigos.", "Business-readable Gherkin validation with PO."),
("What is scenario discovery?", "Process of finding scenarios through conversation, not solo writing. Techniques: Example Mapping, Three Amigos, story mapping. Ask \"what could go wrong?\" for negative scenarios. Edge cases emerge from group discussion. Never automate scenarios discovered alone by QA.", "Collaborative scenario identification process."),
("What is BDD for microservices?", "Each service team owns feature files for its API behavior. Cross-service scenarios test integration flows. Contract scenarios verify service interfaces. Shared step library for common patterns (auth, pagination). Independent execution per service in CI.", "Microservice BDD organization model."),
("What is the BDD testing pyramid?", "Many API/service scenarios (fast, stable), fewer integration scenarios, minimal UI E2E scenarios. BDD applies at all levels — not just UI. Most Gherkin scenarios should be API-level for speed. UI scenarios for critical user journeys only.", "BDD applied across test pyramid layers."),
("How do you handle BDD training for developers?", "Developers write step definitions, not Gherkin. Train on: reading Gherkin, implementing step defs, Page Object pattern. Joint session with QA on Three Amigos. Developers attend first Three Amigos as observers. Gradually participate in scenario writing.", "Developer role clarity in BDD process."),
("What is BDD success criteria for a team?", "All new stories have Gherkin before development. Three Amigos happening regularly. PO reads and approves scenarios. Living documentation referenced in sprint reviews. Reduced requirement-related defects. Team members across roles contribute to feature files.", "Measurable team BDD adoption indicators."),
("What is BDD failure mode: QA-only Gherkin?", "QA writes feature files without PO or Dev input. Scenarios may not reflect business intent. Dev doesn't understand Gherkin. PO ignores feature files. Becomes traditional automation with Gherkin syntax — loses BDD collaboration value. Fix: mandatory Three Amigos.", "Recognize and fix QA-silo BDD anti-pattern."),
("What is BDD failure mode: 100% UI coverage?", "All scenarios test through UI — slow, brittle, expensive to maintain. BDD value is behavior specification, not UI testing. API and service-level scenarios are faster and more stable. Reserve UI scenarios for critical user journeys. Follow test pyramid.", "Test pyramid applied to BDD scenario distribution."),
("How do you write BDD scenarios for negative cases?", "Explicit negative scenario: \"Login with invalid password shows error\". Use Examples table for multiple invalid inputs. Tag @negative. One failure condition per scenario. Then step verifies specific error message. Don't combine multiple negative cases in one scenario.", "Negative scenario writing with clear assertions."),
("What is story mapping vs BDD?", "Story mapping: big-picture visualization of user journey across epics. BDD: detailed behavior examples for individual stories. Story mapping identifies WHAT to build. BDD specifies HOW it should behave. Complementary — story map feeds into Three Amigos scenarios.", "Complementary planning techniques."),
("How do you maintain ubiquitous language glossary?", "Shared document (Confluence/Wiki) listing business terms and definitions. Updated during Three Amigos when new terms emerge. Referenced when writing Gherkin. New team members read glossary during onboarding. Terms used identically in features, code, and discussions.", "Living glossary maintenance process."),
("What is BDD role of QA in Agile?", "QA facilitates Three Amigos, leads Gherkin writing, automates scenarios, maintains framework. QA shifts from \"test at end\" to \"specify behavior upfront\". QA ensures scenarios are testable and automatable. QA coaches PO and Dev on BDD practices.", "QA as BDD facilitator, not just automator."),
("How do you present BDD value to management?", "Show: reduced requirement defects (metrics), faster release confidence, living documentation reducing onboarding time, automated regression saving manual effort. Demo: PO reads Gherkin and confirms it matches intent. Calculate time saved vs manual regression.", "Business case for BDD investment."),
("What is Cucumber vs Behave vs SpecFlow?", "Cucumber-JVM: Java/Kotlin. Behave: Python. SpecFlow/Reqnroll: .NET. All use Gherkin syntax. Choose based on project tech stack. Concepts identical across implementations. Skills transfer between tools — Gherkin and BDD process are universal.", "Tool-agnostic BDD understanding."),
("What is periodic BDD retrospective?", "Monthly team retrospective on BDD practice: Are Three Amigos happening? Feature file quality? Scenario execution time? Flaky scenarios? Step definition maintainability? Action items for improvement. Continuous improvement of BDD process, not just tools.", "Continuous BDD process improvement mindset."),
("How do you handle conflicting scenarios in BDD?", "Two scenarios testing contradictory behavior indicates ambiguous requirements. Escalate to PO for clarification during Three Amigos. Don't automate until resolved. Document decision in scenario comment or linked Jira ticket. Conflicting scenarios signal communication gap.", "Conflict resolution through collaboration, not unilateral decision."),
]

block += '<h3>Top 50 BDD Questions</h3>\n\n'
for i, (q, a, e) in enumerate(bdd, 1):
    block += qa(i, q, a, e)

# Framework 50
fw = [
("How do you implement Page Object Model?", "Each web page is a Java class with locators as private fields and action methods. Constructor takes WebDriver. Methods represent user actions: login(String user, String pass). Tests/step defs call page methods, never access locators directly. BasePage class for common methods: click, type, wait.", "POM class structure with constructor injection of driver."),
("What is Page Factory pattern?", "PageFactory.initElements(driver, this) initializes @FindBy annotated elements lazily. @FindBy(id=\"email\") private WebElement email. Reduces boilerplate. Limitation: stale elements on dynamic pages. Prefer explicit waits in methods over @FindBy for AJAX-heavy applications.", "Page Factory with @FindBy and stale element caveat."),
("What is a hybrid automation framework?", "Combines Keyword-Driven (action keywords in Excel/JSON), Data-Driven (DataProvider/Excel), and Page Object Model. TestNG/Cucumber orchestrates. Keywords map to Java methods. Data externalized. POM handles UI. Maximizes reusability for teams with varied skill levels.", "How hybrid layers interact in practice."),
("What is DriverFactory pattern?", "Centralized WebDriver creation: getDriver() returns ThreadLocal driver. switch(browser) creates ChromeDriver, FirefoxDriver, etc. based on config. quitDriver() cleans up. Single point to change driver configuration. All tests use DriverFactory, never new ChromeDriver() directly.", "ThreadLocal DriverFactory implementation."),
("What is ConfigReader utility?", "Loads properties file based on environment: config-dev.properties, config-staging.properties. get(\"url\") returns property value. System property override: -Durl=... takes precedence. Singleton or static utility. Used by DriverFactory, API clients, DB connections throughout framework.", "Environment-aware config loading pattern."),
("How do you read Excel test data?", "Apache POI library reads .xlsx files. ExcelReader utility: getSheetData(String sheetName) returns Object[][]. DataProvider calls ExcelReader. Column headers map to test parameters. Keep test data in src/test/resources/testdata/. Separate data from code.", "POI-based Excel data provider integration."),
("How do you implement screenshot utility?", "ScreenshotUtil.capture(driver, name) saves PNG to target/screenshots/. Called from TestNG listener onTestFailure or Cucumber @After hook. Timestamp + test name in filename. Attach to ExtentReports/Allure. Create directory if not exists. Clean old screenshots periodically.", "Screenshot capture on failure integration."),
("What is a wait utility class?", "WaitUtil with methods: waitForVisible(locator), waitForClickable(locator), waitForText(locator, text). Centralizes WebDriverWait with configurable timeout from properties. FluentWait for polling interval customization. All page objects use WaitUtil instead of inline waits.", "Centralized explicit wait utility design."),
("What is a BaseTest class?", "Abstract class with @BeforeMethod/@AfterMethod for driver init/quit. @BeforeSuite for config loading. All test classes extend BaseTest. Provides getDriver(), config access. Listeners registered here or in testng.xml. Cucumber: hooks replace BaseTest lifecycle.", "BaseTest lifecycle for TestNG test classes."),
("What is a BasePage class?", "Parent class for all page objects. Common methods: click(WebElement), type(WebElement, text), isDisplayed(locator). Initialize WebDriverWait in constructor. All pages extend BasePage. Reduces duplication across page objects. Navigation methods: getTitle(), getCurrentUrl().", "Shared page object methods in base class."),
("How do you design API client wrapper?", "ApiClient class wraps REST Assured: get(endpoint), post(endpoint, body), put, delete. Handles auth header injection, base URI from config, common assertions. Service classes per resource: UserService extends ApiClient. Step definitions call service methods, not raw REST Assured.", "Service object pattern for API testing."),
("How do you implement database utility?", "DBUtil with getConnection(), query(sql, params), execute(sql, params), querySingle(). Uses JDBC with PreparedStatement for SQL injection prevention. Connection pool (HikariCP) for parallel tests. Read DB config from ConfigReader. Close connections in @AfterSuite.", "JDBC utility with connection pooling for parallel."),
("How do you structure Maven project for automation?", "src/test/java: tests, steps, pages, utils. src/test/resources: features, config, testdata. pom.xml: dependencies, surefire plugin, suite XML. testng.xml in resources/suites/. Separate modules for large projects: core, ui-tests, api-tests. .gitignore: target/, test-output/, screenshots/.", "Standard Maven automation project structure."),
("How do you implement logging in framework?", "Log4j2 or SLF4J with log4j2.xml configuration. Logger per class. Log test start/end, action steps, errors. Separate log file per test run. Thread name in log pattern for parallel debugging. Log level configurable via properties: DEBUG for dev, INFO for CI.", "Structured logging with parallel thread identification."),
("How do you integrate ExtentReports?", "ExtentManager singleton initializes ExtentReports in @BeforeSuite. Listener or hook creates ExtentTest per scenario. Log pass/fail with screenshots. flush() in @AfterSuite. SparkReporter for modern HTML dashboard. Configure report path, theme, system info in extent.properties.", "ExtentReports lifecycle with listener integration."),
("How do you integrate Allure reporting?", "allure-testng or allure-cucumber7-jvm dependency. @Step on page object methods. @Attachment for screenshots. allure.properties configures results directory. Generate: allure serve target/allure-results. Categories for failure classification. Trend history in Allure Docker Service.", "Allure setup with step-level reporting."),
("How do you design CI/CD pipeline for automation?", "Stages: Build → Smoke Test → Deploy Staging → Regression → Report. Parameterized: SUITE, ENV, BROWSER. Publish reports as artifacts. Slack/email on failure. Quality gate: smoke must pass for merge. Nightly full regression. Parallel agents for cross-browser.", "Complete CI/CD pipeline design for test automation."),
("How do you use Docker for test automation?", "Dockerfile: base image + Java + Maven + Chrome. docker-compose.yml: test app + selenium grid + test runner. Run: docker-compose up --abort-on-container-exit. Consistent environment across local and CI. Volume mount for reports. Pre-built images: selenium/standalone-chrome.", "Docker-based test execution environment."),
("How do you configure Selenium Grid?", "Hub-node architecture. hub:4444 receives tests, nodes execute. docker-compose for local grid. Capabilities: browserName, platform. testng.xml parallel tests connect to grid URL. Cloud alternative: BrowserStack/Sauce Labs. Monitor node capacity vs thread-count.", "Grid setup and capacity planning."),
("What is cloud browser testing?", "BrowserStack, Sauce Labs, LambdaTest provide managed browsers/devices. Capabilities builder sets browser/OS/version. RemoteWebDriver connects to cloud URL. Parallel cross-browser without local infrastructure. Cost per minute — optimize test efficiency. Integrate with CI via plugins.", "Cloud provider integration for cross-browser testing."),
("How do you manage test environments?", "Config properties per environment: dev, staging, prod-sanity. Jenkins parameter selects environment. Never run destructive tests on production. Environment health check in @BeforeSuite — skip if unavailable. Separate test accounts per environment. Document environment URLs and credentials policy.", "Multi-environment management without credential leaks."),
("How do you manage secrets in automation?", "Never commit passwords/API keys to git. Jenkins credentials store injects at runtime. Environment variables: System.getenv(\"API_KEY\"). Azure Key Vault / AWS Secrets Manager for enterprise. .gitignore secrets files. ConfigReader reads from env vars, not properties files, for sensitive data.", "Secrets management best practices."),
("What is test tagging strategy?", "Three tiers: @smoke (critical, every commit), @regression (full, nightly), @sanity (post-deploy). Module tags: @login, @checkout. Type tags: @ui, @api. Cross-cutting: @negative, @wip. Document tag definitions. CI jobs map to tag combinations.", "Hierarchical tag strategy with CI mapping."),
("How do you organize test suites?", "Separate testng.xml per suite: smoke.xml, regression.xml, api.xml. Each specifies groups/tags, parallel settings, listeners. CI job parameter selects suite. Smoke: 10-15 min. Regression: 1-2 hours. Sanity: 5 min post-deploy. Review suite composition monthly.", "Suite organization by execution frequency and scope."),
("How do you manage flaky tests?", "Track flakiness rate per test over 10 runs. Investigate: timing, data, environment. Fix root cause, don't just retry. Quarantine persistently flaky tests (@quarantine tag). Jira ticket for each flaky test. Target: less than 2% flaky rate. Retry as temporary measure only.", "Systematic flaky test management process."),
("What is framework maintenance strategy?", "Monthly: dependency updates, remove obsolete tests. Quarterly: refactor duplicated code, optimize slow tests. Version pin Selenium/TestNG. Automated dependency PRs with smoke validation. Code review for test code same as production code. Deprecation policy for old patterns.", "Long-term framework ownership plan."),
("What design patterns apply to automation?", "POM (Page Object), Factory (DriverFactory), Singleton (ConfigReader), Builder (TestDataBuilder), Strategy (BrowserStrategy), Facade (ApiClient), Observer (Listener). Don't over-engineer — use patterns where they reduce duplication. Match team's Java skill level.", "Appropriate pattern selection, not pattern overuse."),
("How do you implement Factory pattern for browsers?", "BrowserFactory.create(String browser) returns WebDriver. Switch on browser type: chrome, firefox, edge. Read headless, window size from config. Extensible: add new browser by adding case. DriverFactory delegates to BrowserFactory. Keeps driver creation logic centralized.", "BrowserFactory with config-driven browser selection."),
("How do you implement Builder pattern for test data?", "UserBuilder.newUser().withName(\"John\").withEmail(\"j@t.com\").withRole(\"admin\").build(). Fluent API for readable test data creation. Default values for optional fields. Used in @BeforeMethod or step definitions. Reduces test data boilerplate.", "Builder pattern for readable test data creation."),
("How do you implement Strategy pattern for browsers?", "BrowserStrategy interface: createDriver(), getCapabilities(). ChromeStrategy, FirefoxStrategy implementations. BrowserFactory selects strategy based on config. Enables adding browsers without modifying factory. Cleaner than switch-case for many browser types.", "Strategy pattern for extensible browser support."),
("How do you review automation code?", "Checklist: no static WebDriver, no Thread.sleep, locators not in tests, proper waits, data cleanup, meaningful assertions, no hardcoded values, proper exception handling. Same PR process as app code. Require 1 approval for test code PRs. Lint with Checkstyle/SpotBugs.", "Test code review standards and checklist."),
("How do you handle email verification in tests?", "MailHog or MailSlurp for test email capture. API retrieves email by recipient. Extract verification link/OTP from email body. Use in step definition to complete verification flow. Self-hosted MailHog in Docker for CI. Never use real email accounts in automation.", "Test email service integration pattern."),
("How do you validate PDF content in tests?", "Apache PDFBox library extracts text from downloaded PDF. Compare extracted text with expected content. Verify PDF downloaded successfully (file exists, size > 0). Use in @Then step for invoice/report validation. Store expected PDFs in test resources for comparison.", "PDF validation approach in test automation."),
("How do you implement custom annotations?", "Define @RequiresLogin, @CleanupData annotations. IAnnotationTransformer or IInvokedMethodListener processes them at runtime. @RequiresLogin triggers login in beforeInvocation. Self-documenting test requirements. Advanced pattern for framework governance.", "Custom annotation processing in TestNG listeners."),
("How do you version control automation framework?", "Git with feature branch workflow. testng.xml and feature files in repo. Config templates committed, secrets excluded. Tag releases: v1.0-smoke-suite. CHANGELOG for framework changes. Semantic versioning for shared libraries. Branch protection on main.", "Git workflow for test automation codebase."),
("How do you handle property file management?", "config.properties for defaults. config-{env}.properties for environment overrides. Maven resource filtering for CI values. ConfigReader merges: system props > env props > default props. Never duplicate keys across files. Document all properties in README.", "Property precedence and environment override pattern."),
("How do you implement reporting aggregation?", "Merge TestNG XML + Cucumber JSON into unified dashboard. Jenkins aggregates across parallel jobs. Custom script parses both formats into single HTML. Track pass rate, duration, flaky count trends. Grafana dashboard for historical metrics.", "Multi-format report aggregation strategy."),
("How do you classify test failures?", "Categories: AUT (application bug), TEST (automation bug), ENV (environment issue), DATA (test data problem). Listener classifies based on exception type and context. Report shows category breakdown. Helps prioritize fixes: AUT → Jira bug, TEST → fix automation.", "Failure classification taxonomy for triage."),
("How do you build test metrics dashboard?", "Track: pass rate, execution time, flaky rate, scenario count, failure categories. Source: TestNG XML, Cucumber JSON, CI build data. Grafana or custom HTML dashboard. Weekly email summary to team. Trend over 30/90 days. Alert on pass rate drop below threshold.", "Metrics-driven quality visibility."),
("How do you handle multi-module Maven projects?", "Parent pom.xml with dependencyManagement. Modules: automation-core (utils, pages), ui-tests, api-tests. Each module has own testng.xml. CI runs modules in parallel or sequence. Shared dependencies managed in parent. Reusable core module published as internal artifact.", "Multi-module structure for large automation projects."),
("What is framework versioning strategy?", "Semantic versioning: MAJOR (breaking changes), MINOR (new features), PATCH (fixes). Pin framework version in consumer projects. Release notes for each version. Deprecation warnings before removing features. Backward compatibility for step definitions and config.", "Version management for shared automation libraries."),
("How do you implement action class (Actions API)?", "ActionsUtil wraps Selenium Actions class: dragAndDrop, hover, doubleClick, rightClick, key combinations. Methods take WebElement parameters. Used by page objects for complex interactions. Centralized action logic with proper wait before action.", "Actions API wrapper for complex UI interactions."),
("How do you handle YAML configuration?", "SnakeYAML library parses .yml config files. Nested structure for complex config: environments > staging > url. More readable than properties for hierarchical config. ConfigReader supports both YAML and properties. Choose based on config complexity.", "YAML vs properties for complex configuration."),
("How do you implement test data builder?", "TestDataBuilder creates complex test objects fluently. UserBuilder, OrderBuilder with sensible defaults. Reduces test setup code. Integrates with @BeforeMethod and step definitions. Faker library for random realistic data. Builder output used in API setup and UI verification.", "Fluent builder for complex test data setup."),
("How do you implement Facade for API testing?", "ApiFacade provides simplified interface: createUserAndLogin() handles registration, login, token storage in one call. Hides multi-step API interactions from step definitions. Step def calls facade, facade orchestrates service calls. Reduces step definition complexity.", "Facade simplifying multi-step API interactions."),
("How do you handle file download verification?", "ChromeOptions: setDownloadPath to known directory. After click download, WaitUtil waits for file to appear. Verify filename and size. Clean download directory in @AfterMethod. Remote grid: enable download in node config. Assert file content if needed.", "Download verification with wait for file existence."),
("How do you implement listener framework?", "ListenerFactory registers listeners based on config: screenshot listener, logging listener, report listener. Enabled/disabled via properties. BaseListener abstract class with common logic. Register in testng.xml or @Listeners. Extensible: add new listener without changing existing code.", "Pluggable listener architecture design."),
("How do you handle window/tab switching?", "WindowHelper utility: getCurrentHandle(), switchToWindow(handle), closeCurrentSwitchToMain(). Wait for new window after click. Used in page objects for popup handling. Step definitions call page object methods. Always return to main window in finally block.", "Multi-window handling utility pattern."),
("How do you implement retry in framework?", "IRetryAnalyzer with max 2 retries. IAnnotationTransformer applies globally. Retry only on specific exceptions: TimeoutException, StaleElementReferenceException. Log retry count in listener. Report shows retry attempts. Quarantine test if retry rate exceeds 30%.", "Smart retry with exception filtering and quarantine."),
("How do you onboard new team members to framework?", "Day 1: README, project structure walkthrough. Day 2: Run existing tests, read feature files. Day 3: Write simple scenario with pair programming. Day 4: Implement step definitions. Day 5: Solo task with code review. Documentation: architecture diagram, coding standards, common patterns.", "Structured onboarding plan for automation framework."),
]

block += '<h3>Top 50 Framework Design Questions</h3>\n\n'
for i, (q, a, e) in enumerate(fw, 1):
    block += qa(i, q, a, e)

# Scenario 50
sc = [
("How do you investigate flaky tests?", "Check last 10 runs: pass/fail pattern. Reproduce locally 20 times. Add logging around failure point. Common causes: timing, shared data, environment diff. Fix root cause. Temporary: retry with limit. Track in flaky test register. Target fix within 1 sprint.", "Systematic root cause analysis, not blind retry."),
("How do you debug parallel test failures?", "Run with thread-count=1 to confirm sequential pass. Add thread name to logs. Check ThreadLocal driver implementation. Look for static shared state. Verify unique test data per thread. Run 2 threads locally, then scale. Common fix: ThreadLocal + unique data.", "Parallel-specific debugging methodology."),
("How do you analyze CI-only failures?", "Compare: browser version, OS, screen size, timing, env config. Run CI Docker image locally. Enable verbose logging in CI. Capture artifacts: screenshots, logs, HAR. Check if parallel in CI but sequential locally. Increase wait timeouts as temporary diagnostic.", "Local vs CI environment comparison approach."),
("How do you handle test timeout issues?", "Identify slow step via timeline report. Root cause: excessive waits, slow API, heavy page. Fix: optimize waits, mock slow services, API setup instead of UI. Set realistic timeOut on @Test. Never just increase timeout without investigation.", "Root cause fix, not timeout inflation."),
("How do you fix StaleElementReferenceException?", "Element changed in DOM after find. Fix: re-find element before interaction. Use explicit wait with fresh lookup. Page Object method re-locates element each call. Avoid storing WebElement as instance variable on dynamic pages. ExpectedConditions.refreshed() for re-fetch.", "Re-find element pattern for dynamic pages."),
("How do you handle session expired mid-test?", "Detect login page redirect in @BeforeStep or page object guard method. Re-authenticate via API (fast) and continue. Or fail with clear message: \"Session expired\". Prevention: refresh token in long-running tests. Set appropriate session timeout in test environment.", "Session recovery or clear failure strategy."),
("How do you fix reports not generating in CI?", "Check report output path exists and is writable. Verify listener registered in testng.xml. Ensure @AfterSuite flush() runs even on failure (alwaysRun=true). Check CI archives correct directory. Plugin paths relative to working directory. Permissions on CI agent.", "CI-specific report path and permission debugging."),
("How do you fix screenshots not captured on failure?", "Verify listener @AfterMethod runs on failure (alwaysRun=true). Check driver not null and not quit before screenshot. RemoteWebDriver: screenshot capability enabled. Path writable in CI. Cucumber: @After hook checks scenario.isFailed(). Debug: log in listener to confirm invocation.", "Listener execution order and driver state debugging."),
("How do you handle DB connection pool exhaustion?", "Limit parallel thread-count to match pool size. HikariCP: maxPoolSize = thread-count + 2. Close connections in @AfterMethod/@AfterSuite. Don't create connection per query — reuse pool. Monitor pool metrics. Separate read-only pool for validation queries.", "Connection pool sizing for parallel tests."),
("How do you fix test data collision in parallel?", "Unique data per thread: UUID suffix on emails, usernames. Separate DB schema per thread (advanced). API creates fresh data in @BeforeMethod. Never use hardcoded shared accounts. Cleanup in @AfterMethod. Data isolation is mandatory for parallel reliability.", "Unique test data generation per parallel thread."),
("How do you handle browser version mismatch?", "WebDriverManager auto-matches driver to browser. Pin browser version in CI Docker image. Grid: specify browser version in capabilities. Cloud: set version in capabilities. Document supported browser versions. CI matrix tests specific versions.", "Browser/driver version alignment strategy."),
("How do you fix headless vs headed test differences?", "Headless may render differently: set window size explicitly. Disable headless for debugging, enable for CI. ChromeOptions: --window-size=1920,1080. Some features (PDF viewer, downloads) behave differently headless. Test critical flows in both modes.", "Headless configuration for consistent rendering."),
("How do you handle SSL certificate errors in CI?", "ChromeOptions: --ignore-certificate-errors for test environments only. Never in production tests. Import cert to truststore for proper fix. Custom TrustManager for REST Assured API tests. Document which environments have self-signed certs.", "Test environment SSL handling, not production bypass."),
("How do you configure proxy in Selenium Grid?", "Proxy capability in DesiredCapabilities. HTTP proxy for corporate networks. Grid node proxy settings in node config. REST Assured: RestAssured.proxy(). Test proxy connectivity in @BeforeSuite. Document proxy requirements for team.", "Proxy configuration for corporate CI environments."),
("How do you verify file downloads in automation?", "Set download directory via browser preferences. Wait for file existence with polling. Verify filename pattern and file size. Parse content (CSV, PDF, Excel). Clean download folder in @AfterMethod. Grid: configure download path on node.", "Reliable download verification pattern."),
("How do you handle file upload in headless mode?", "sendKeys with absolute file path to hidden input element. Works in headless. File must exist on CI agent. Store test files in src/test/resources/. Remote grid: LocalFileDetector. Never use Robot class for file dialog.", "sendKeys upload approach for headless CI."),
("How do you handle iFrame testing failures?", "Switch to frame before interaction: driver.switchTo().frame(locator). Interact with elements inside frame. switchTo().defaultContent() after. Nested frames: switchTo().parentFrame(). Wait for frame availability. Encapsulate in page object methods.", "Frame switching with proper context cleanup."),
("How do you handle JavaScript alert dialogs?", "Alert alert = wait.until(ExpectedConditions.alertIsPresent()). alert.accept() or dismiss(). Verify alert text before accepting. Handle unexpected alerts in @AfterStep to prevent next step failure. Don't use Robot for alerts.", "ExpectedConditions.alertIsPresent() pattern."),
("How do you handle cookie domain issues?", "Delete all cookies in @BeforeMethod for clean state. Set cookies via Selenium for auth bypass. Verify cookie domain matches application domain. Cross-subdomain tests: set domain explicitly. API-set cookies may differ from Selenium-set — test both paths.", "Cookie management for test isolation."),
("How do you handle multi-window test failures?", "Store main window handle before opening popup. Switch to new window by iterating handles. Perform actions in popup. Close popup, switch back to main. Wait for new window with WebDriverWait. WindowHelper utility encapsulates logic.", "Window handle management pattern."),
("How do you fix AJAX wait failures?", "Never use Thread.sleep for AJAX. Explicit wait: ExpectedConditions.invisibilityOfElementLocated(loader) or visibilityOfElementLocated(content). Wait for specific AJAX indicator disappearance. FluentWait with polling. Set reasonable timeout (15-30s) in config.", "AJAX-specific wait conditions."),
("How do you handle test environment unavailable?", "@BeforeSuite health check: ping API, verify DB connection. SkipException if environment down. CI: retry environment provisioning. Alert team via Slack. Don't waste 30 min running tests against dead environment. Log clear message: \"Staging unavailable\".", "Environment health check before suite execution."),
("How do you test feature flags?", "API or DB sets feature flag state in @BeforeMethod. Test both enabled and disabled scenarios with tags: @flag-on, @flag-off. Reset flag in @AfterMethod. Coordinate with dev team on flag names. Don't test both states in same scenario.", "Feature flag setup/teardown per scenario."),
("How do you handle OTP in automation?", "Test environment: disable OTP or use fixed test OTP (123456). API bypass: generate OTP via test API endpoint. MailHog captures OTP email, extract code. Never automate real SMS OTP. Document OTP bypass approach for test environment.", "Test environment OTP bypass strategy."),
("How do you handle CAPTCHA in automation?", "Disable CAPTCHA in test environment (recommended). Test API bypass endpoint. Use test-only CAPTCHA key that always passes. Never use CAPTCHA solving services in CI. If CAPTCHA mandatory, test up to CAPTCHA step and verify it appears.", "CAPTCHA disable/bypass in test environments."),
("How do you verify email in automation?", "MailHog/MailSlurp captures test emails. API query: get latest email for recipient. Assert subject, body content, links. Extract verification URL and navigate. Self-hosted MailHog in Docker Compose with test app.", "Email testing with mail capture service."),
("How do you test OAuth flows?", "Test OAuth provider mock or sandbox. Automate authorization flow in dedicated scenarios. API shortcut: obtain token directly for non-OAuth scenarios. Store client ID/secret in CI credentials. Scope OAuth tests with @oauth tag.", "OAuth test strategy with mock/sandbox provider."),
("How do you handle JWT token refresh in tests?", "API login obtains JWT in @BeforeMethod. Store in ThreadLocal or context. Refresh token before expiry in long scenarios. Inject as Authorization header for API steps. Cookie/localStorage for UI tests. Handle 401 by re-authenticating.", "Token lifecycle management in test suite."),
("How do you test rate limiting?", "Verify 429 status code after exceeding limit. Use dedicated rate-limit test account. Reset rate limit via test API or wait. Tag @rate-limit for isolated execution. Don't run rate limit tests in shared regression — affects other tests.", "Isolated rate limit testing approach."),
("How do you optimize test execution time?", "API setup instead of UI login. Headless browser. Parallel execution. Remove redundant @BeforeMethod steps. Cache static test data. Skip non-critical scenarios in smoke. Profile with timeline report. Target: smoke 10 min, regression 1 hour.", "Data-driven optimization priorities."),
("How do you test payment gateway integration?", "Use sandbox/test mode API keys. Test card numbers provided by gateway (4111111111111111). Verify success, decline, and error flows. Never use real cards. Mock gateway for unit tests, sandbox for E2E. Tag @payment for isolated execution.", "Payment sandbox testing with test cards."),
("How do you handle WebSocket testing?", "Java WebSocket client connects to test endpoint. Send/receive messages programmatically. Verify message content and order. UI test: verify WebSocket-driven UI updates with explicit wait. Close connection in @AfterMethod.", "WebSocket client testing approach."),
("How do you test GraphQL APIs?", "HTTP POST with query in body. REST Assured or HttpClient. Verify response data path. Test error cases: invalid query, missing variables. Schema validation against GraphQL schema. Tag @graphql scenarios separately.", "GraphQL query testing in automation."),
("How do you test responsive design?", "Set window sizes: 1920x1080 (desktop), 768x1024 (tablet), 375x667 (mobile). Verify element visibility/layout at each size. Chrome DevTools mobile emulation. Cloud services for real device testing. Tag @responsive for separate execution.", "Viewport-based responsive testing."),
("How do you integrate performance testing?", "Separate performance suite with JMeter/Gatling. Functional tests verify correctness, performance tests verify speed. Don't mix load testing with functional regression. Baseline response time assertions in API tests. Alert on response time degradation trend.", "Separation of functional and performance testing."),
("How do you test in production safely?", "Read-only sanity tests only: homepage loads, API health check. No create/update/delete operations. Dedicated prod-sanity testng.xml. Run post-deployment only. @prod tag with strict CI restriction. Monitor test impact on production metrics.", "Safe production sanity testing guardrails."),
("How do you verify deployment with automation?", "Post-deploy sanity suite: 5-10 critical scenarios. Run against newly deployed environment. Gate: deployment rolls back if sanity fails. Smoke within 5 minutes of deploy. Results notify deployment team. Separate from full regression.", "Post-deployment verification gate process."),
("How do you test rollback scenarios?", "Deploy new version, run sanity. Simulate rollback to previous version. Re-run sanity against rolled-back version. Verify data integrity after rollback. Requires automated deployment pipeline. Tag @rollback for manual/scheduled execution.", "Rollback verification test process."),
("How do you test blue-green deployment?", "Run regression against green environment before switch. Post-switch sanity on green. Keep blue tests ready for rollback verification. DNS/load balancer switch automated. Test both environments during transition period.", "Dual-environment deployment testing."),
("How do you test canary releases?", "Run smoke against canary instance with 5% traffic. Compare metrics: error rate, response time vs stable. Automated canary analysis (ACA) in CI. Rollback canary if metrics degrade. Functional tests target canary URL specifically.", "Canary validation with metric comparison."),
("How do you handle localization testing?", "Set browser locale/language preferences. Verify UI text in expected language. Test date/number formatting per locale. Data-driven: Examples table with locale and expected text. Tag @i18n for separate execution. Store translations in test data files.", "Locale-specific UI verification approach."),
("How do you integrate accessibility testing?", "Axe-core library integrated with Selenium. Run accessibility scan after page load. Assert zero critical violations. Tag @a11y scenarios. Report WCAG violations with element details. Run in CI but not blocking initially — trend toward zero violations.", "Automated accessibility scanning integration."),
("How do you test third-party widgets?", "Mock third-party in test environment where possible. If real widget required: wait for widget load indicator. Test integration points, not widget internals. Isolate widget failures with @third-party tag. Fallback: verify placeholder when widget unavailable.", "Third-party widget test isolation strategy."),
("How do you handle chart/graph verification?", "Extract chart data via JavaScript executor: return chart data from canvas/SVG. Compare data values programmatically. Visual regression for chart appearance (optional). Don't rely on pixel comparison — validate underlying data.", "Data-level chart validation over visual comparison."),
("How do you test Excel export validation?", "Download file, read with Apache POI. Verify row count, column headers, cell values. Compare with expected test data. Clean up downloaded files. Handle large exports with streaming reader.", "POI-based export content verification."),
("How do you handle network HAR capture for debugging?", "BrowserMob Proxy or Selenium 4 devtools for HAR capture. Save HAR on test failure. Analyze failed requests, response codes, timing. Attach HAR to bug reports. Enable only on failure to avoid performance impact.", "Network-level debugging on failure."),
("How do you coordinate load and functional testing?", "Never run load tests against shared test environment with functional tests. Separate environments: func-test, load-test. Schedule load tests off-hours. Functional tests verify features; load tests verify scalability. Different tools, different environments, different schedules.", "Environment separation for load vs functional tests."),
("How do you handle mobile web testing?", "Chrome mobile emulation with device metrics. Cloud services (BrowserStack) for real devices. Responsive design testing at mobile viewports. Touch action simulation via Actions class. Separate @mobile tag suite. Appium for native apps — different framework.", "Mobile web vs native app testing distinction."),
("How do you manage test execution reporting failures?", "Verify report plugin paths are writable. Check listener registration. @AfterSuite flush with alwaysRun=true. CI archives correct output directory. Fallback: generate report programmatically in IReporter. Log report generation status.", "Report generation failure troubleshooting."),
("How do you handle A/B test automation?", "API sets user bucket before test. Verify A variant experience for bucket A user. Separate scenarios for each variant. Reset bucket in @AfterMethod. Coordinate with product team on experiment flags. Tag @ab-test for isolated execution.", "A/B test bucket assignment in automation."),
]

block += '<h3>Top 50 Scenario-Based Questions</h3>\n\n'
for i, (q, a, e) in enumerate(sc, 1):
    block += qa(i, q, a, e)

block += '</section>\n'

# Read file and replace templated section
path = r'c:\Users\anideshm\Cursor Implementation\Learning notes\testng_sections_30_35.html'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# Find start marker (second Intermediate 35 - Cucumber)
marker_start = content.find('<h3>Top 100 Cucumber Questions</h3>')
marker_mid = content.find('<h4>Intermediate (35)</h4>', marker_start)
marker_end = content.find('<section id="section-34"', marker_mid)

if marker_mid == -1 or marker_end == -1:
    print('ERROR: markers not found', marker_mid, marker_end)
else:
    new_content = content[:marker_mid] + block + content[marker_end:]
    with open(path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    s33_start = new_content.find('section-33')
    s33_end = new_content.find('section-34')
    s33_section = new_content[s33_start:s33_end]
    print(f'Replaced templated content. Section 33 lines: {s33_section.count(chr(10))}')
    print(f'Total file lines: {new_content.count(chr(10))}')
    print(f'Questions in section 33: {s33_section.count("<strong>Q")}')
