// Question-specific answers for Section 40 interview prep
function getQA(q) {
  const db = ANSWERS[q];
  if (db) return db;
  return inferAnswer(q);
}

function inferAnswer(q) {
  const l = q.toLowerCase();
  if (l.includes('how') || l.includes('fix') || l.includes('strategy') || l.includes('approach') || l.includes('debug')) {
    return {
      a: `Describe a systematic approach: identify root cause, implement a durable fix (not a workaround), and validate across environments. Reference a real project example where you applied this. Explain tools used (DevTools, logs, explicit waits, unique locators) and how you prevented recurrence through framework improvements or CI checks.`,
      e: `Structured problem-solving with a concrete past example — not theoretical advice only.`
    };
  }
  if (l.includes(' vs ') || l.includes('difference')) {
    return {
      a: `State the definition of each side, then compare on key dimensions: purpose, performance, thread safety, and use cases. Give a test automation example showing when you pick one over the other. Mention a common mistake candidates make when conflating the two.`,
      e: `Clear side-by-side comparison with a practical "when to use which" recommendation.`
    };
  }
  if (l.includes('internal working') || l.includes('working?')) {
    return {
      a: `Explain the underlying data structure and algorithm step-by-step (insert, lookup, remove). Mention time complexity for key operations. Relate to real usage in test frameworks — e.g., storing test data, caching locators, or parallel-safe collections.`,
      e: `Deep enough to draw or whiteboard the internal structure — not just API surface.`
    };
  }
  if (l.includes('what is') || l.endsWith('?')) {
    return {
      a: `Define the concept in one sentence, then explain why it matters in Java/Selenium automation with a short code or framework example. Cover one best practice and one common pitfall. Connect to how you have used it in a real test project.`,
      e: `Definition plus practical automation context — shows you have applied it, not just read about it.`
    };
  }
  return {
    a: `Provide a structured answer: definition, practical example in test automation, best practice, and one trade-off. Relate to framework design or debugging where relevant. Keep the answer focused and under 60 seconds when spoken aloud.`,
    e: `Confident, concise answer demonstrating hands-on experience.`
  };
}

const ANSWERS = {
  // ===== JAVA OOP (30) =====
  'What is a class?': { a: 'A class is a blueprint that defines fields (state) and methods (behavior) for objects. It does not consume memory until instantiated. In automation, each Page Object is typically a class encapsulating locators and actions. Example: public class LoginPage { private By user = By.id("user"); }', e: 'Mention blueprint vs instance and give a Page Object example.' },
  'What is an object?': { a: 'An object is a runtime instance of a class created with new, stored on the heap with its own state. Two objects of the same class have independent field values. In tests, WebDriver driver = new ChromeDriver() creates a driver object managing a browser session.', e: 'Distinguish reference variable from actual heap object.' },
  'What is a constructor?': { a: 'A constructor initializes object state when new is called; it has no return type and matches the class name. Default constructor is provided if none defined. Page objects use constructors to receive WebDriver: public LoginPage(WebDriver driver) { this.driver = driver; }', e: 'Know default vs custom constructor and this assignment pattern.' },
  'Default vs parameterized constructor?': { a: 'Default constructor takes no arguments (compiler-generated if no constructor defined). Parameterized constructor accepts arguments to initialize fields at creation time. Use parameterized constructors in page objects to inject driver and config. Cannot have return type; overloading allows multiple constructors.', e: 'Explain when you inject dependencies via constructor in framework code.' },
  'What is encapsulation?': { a: 'Encapsulation hides internal state behind private fields and exposes controlled access via public getters/setters. It protects data integrity and allows validation before modification. In frameworks, ConfigReader encapsulates file path and parsing logic — callers use getProperty() without knowing internals.', e: 'Link data hiding to maintainable test utilities.' },
  'What is inheritance?': { a: 'Inheritance (extends) lets a subclass reuse and extend superclass fields and methods — IS-A relationship. BasePage can hold common wait/click helpers; LoginPage extends BasePage. Java supports single class inheritance only. Use when true specialization exists, not just code reuse.', e: 'Give BasePage inheritance example; mention single inheritance limit.' },
  'What is polymorphism?': { a: 'Polymorphism allows a parent reference to point to child objects and invoke overridden methods at runtime. WebDriver driver = new ChromeDriver() — driver reference type is WebDriver, actual object is ChromeDriver. Method overriding enables this; overloading is compile-time polymorphism.', e: 'Distinguish runtime (overriding) from compile-time (overloading) polymorphism.' },
  'What is abstraction?': { a: 'Abstraction hides complex implementation and exposes only essential behavior. Achieved via abstract classes (partial implementation) and interfaces (pure contract). WebDriver interface abstracts browser-specific details — your tests call get() and click() without knowing Chrome vs Firefox internals.', e: 'Connect abstraction to WebDriver interface as real-world example.' },
  'IS-A vs HAS-A relationship?': { a: 'IS-A is inheritance: Dog IS-A Animal (extends). HAS-A is composition: Car HAS-A Engine (field reference). Favor HAS-A when you need flexibility — a TestContext HAS-A WebDriver rather than forcing all tests to inherit from a mega base class. Composition reduces tight coupling.', e: 'Prefer composition for framework utilities; inheritance for true IS-A hierarchies.' },
  'Method overloading?': { a: 'Overloading defines multiple methods with the same name but different parameter lists (type, count, or order) in the same class. Resolved at compile time. Example: click(By locator) and click(WebElement element) in a utility class. Return type alone does not distinguish overloads.', e: 'Compile-time resolution; different parameter lists required.' },
  'Method overriding?': { a: 'Overriding redefines a superclass method in a subclass with the same signature and compatible return type. Resolved at runtime via dynamic dispatch. @Override annotation catches errors. Cannot override static, final, or private methods. Used when BasePage defines click() and MobilePage overrides for touch events.', e: 'Runtime polymorphism; same signature; @Override annotation.' },
  'Can we override static methods?': { a: 'No — static methods belong to the class, not instances. A subclass method with the same signature hides (shadows) the parent static method but does not override it. Calling via parent reference invokes parent version. This is method hiding, not polymorphic overriding.', e: 'Use "method hiding" terminology — not overriding.' },
  'Can we override private methods?': { a: 'No — private methods are not visible to subclasses. If a subclass defines a method with the same signature, it is a new method, not an override. The @Override annotation will cause a compile error if applied. Encapsulation prevents subclass access to private implementation details.', e: 'Private methods are not part of inheritance contract.' },
  'What is super keyword?': { a: 'super refers to the immediate parent class. super() calls parent constructor (must be first statement in constructor). super.method() invokes overridden parent method from subclass. Useful when extending BasePage and calling super.waitForPageLoad() before child-specific actions.', e: 'Mention super() as first line in constructor rule.' },
  'What is this keyword?': { a: 'this refers to the current object instance. Used to disambiguate field vs parameter (this.driver = driver), call other constructors (this(args)), or pass current object. In page objects, this is commonly used for fluent interface method chaining: return this;', e: 'Give fluent page object return this example.' },
  'Abstract class vs interface?': { a: 'Abstract class can have instance fields, constructors, concrete and abstract methods; single inheritance. Interface defines contract (methods); supports multiple implementation; Java 8+ allows default/static methods. Use abstract class for shared state/behavior (BasePage); interface for capability contracts (Retryable, Reportable).', e: 'Trade-off table: state, inheritance, use case.' },
  'What is final class?': { a: 'A final class cannot be extended — String and Integer are final. Prevents subclassing that could break invariants. Use final on utility classes that should not be subclassed (e.g., DriverFactory with private constructor). Declared with final keyword before class keyword.', e: 'String is final — classic interview example.' },
  'What is final method?': { a: 'A final method cannot be overridden by subclasses. Prevents altering critical behavior. Useful for template method pattern where base defines algorithm skeleton and final method enforces step order. Rare in test code but important for security-sensitive or framework-core methods.', e: 'Prevents overriding — different from final variable.' },
  'What is final variable?': { a: 'A final variable can be assigned once — for primitives, value cannot change; for references, reference cannot be reassigned (object contents may still mutate). Use final for locators: private final By loginBtn = By.id("login"); signals immutability of reference.', e: 'Distinguish final reference from immutable object (String is immutable, StringBuilder is not).' },
  'Composition vs inheritance?': { a: 'Inheritance (IS-A) couples subclass to parent hierarchy; composition (HAS-A) embeds objects as fields for flexibility. Prefer composition when behavior can be swapped — a TestRunner HAS-A RetryStrategy rather than extending RetryTest. Composition follows "favor composition over inheritance" principle from Effective Java.', e: 'Effective Java principle — composition for flexibility.' },
  'What is coupling?': { a: 'Coupling measures dependency between classes. Tight coupling (tests directly new ChromeDriver()) makes change hard. Loose coupling (tests use WebDriver interface injected via factory) improves maintainability. Dependency injection and interfaces reduce coupling in automation frameworks.', e: 'Show tight vs loose coupling with driver creation example.' },
  'What is cohesion?': { a: 'Cohesion measures how closely a class\'s methods and fields relate to a single purpose. High cohesion: LoginPage only handles login. Low cohesion: UtilityClass with email, DB, and screenshot methods. High cohesion makes classes easier to test, maintain, and reuse.', e: 'Single Responsibility — one class, one purpose.' },
  'What is static block?': { a: 'Static block runs once when class is first loaded by JVM, before any constructor. Used for static field initialization (loading config.properties into static Map). Order: static fields → static block → main/constructor. Cannot access instance fields inside static block.', e: 'Runs once at class loading — good for config initialization.' },
  'What is instance block?': { a: 'Instance initialization block { } runs before constructor each time an object is created. Used for common initialization shared across constructors. Execution order: static block → instance block → constructor. Rare in test code but shows JVM initialization understanding.', e: 'Know initialization order: static → instance → constructor.' },
  'What is object cloning?': { a: 'Cloning creates a copy of an object. Shallow clone (clone()) copies field values — references are shared. Deep clone copies referenced objects too. Test data objects may need clone to avoid cross-test contamination in parallel runs. Implement Cloneable and override clone() for shallow copy.', e: 'Shallow vs deep clone distinction with parallel test data example.' },
  'Shallow vs deep copy?': { a: 'Shallow copy duplicates object fields but shared references point to same nested objects. Deep copy recursively clones nested objects. In parallel tests, shallow copy of a test data Map still shares inner lists — deep copy isolates each thread. Serialization or manual copy constructors achieve deep copy.', e: 'Parallel test data isolation is the practical hook.' },
  'What is marker interface?': { a: 'Marker interface has no methods — tags a class for JVM/framework treatment. Serializable enables object serialization; Cloneable enables clone(). TestNG uses annotations (@Test) rather than marker interfaces, but concept shows metadata-driven behavior in Java ecosystem.', e: 'Serializable and Cloneable as classic examples.' },
  'What is functional interface?': { a: 'Functional interface has exactly one abstract method (SAM), enabling lambda expressions. @FunctionalInterface annotation is optional but recommended. Examples: Runnable, Callable, Predicate, Function. In tests: Predicate&lt;WebElement&gt; isVisible = e -> e.isDisplayed();', e: 'SAM rule and link to lambda usage in test utilities.' },
  'Diamond problem in Java?': { a: 'Diamond problem occurs when a class inherits conflicting default methods from two interfaces. Java 8 allows multiple interface inheritance but class must override conflicting defaults. Example: if A and B both define default log(), class C implements both and must override log() to resolve ambiguity.', e: 'Java 8 default methods created this — override required to resolve.' },
  'Multiple inheritance in Java?': { a: 'Java does not support multiple class inheritance (one extends only). Supports multiple interface implementation. This avoids diamond problem with classes. A test class can implement ITestListener and IRetryAnalyzer simultaneously while extending BaseTest once.', e: 'Classes: single; interfaces: multiple.' },

  // ===== JAVA STRINGS (20) =====
  'Why is String immutable?': { a: 'String is final with internal char array not exposed for mutation. Immutability enables String pool sharing, thread safety without synchronization, and security (SQL/param safety). Once created, "admin" literal is reused. Use StringBuilder for loop concatenation in test data builders.', e: 'Mention String pool, thread safety, and security benefits.' },
  'What is String pool?': { a: 'String pool (intern pool) stores unique string literals in heap for reuse. String s = "hello" uses pool; new String("hello") creates heap object outside pool. s.intern() adds to pool. Saves memory when same literals appear across framework config keys and test data.', e: 'Literal vs new String() — pool behavior difference.' },
  'new String() vs literal?': { a: 'Literal "test" may reuse pooled instance; new String("test") always creates new heap object. == may differ: literal1 == literal2 is true (same pool ref); new String("test") == "test" is false. Always use equals() for content comparison in assertions.', e: 'Never use == for String content comparison.' },
  '== vs equals() for String?': { a: '== compares memory references (same object?). equals() compares character content (when properly overridden — String does). "a" == new String("a") is false; "a".equals(new String("a")) is true. In test assertions, always use assertEquals(expected, actual) which uses equals().', e: 'Reference vs content — assertEquals uses equals().' },
  'String vs StringBuilder?': { a: 'String is immutable — each modification creates new object ( costly in loops). StringBuilder is mutable, not thread-safe, efficient for concatenation. Build dynamic XPath or JSON in loops with StringBuilder. Use String for constants and final values like locator templates.', e: 'Performance in loops — StringBuilder wins.' },
  'StringBuilder vs StringBuffer?': { a: 'Both mutable. StringBuffer methods are synchronized (thread-safe, slower). StringBuilder is not synchronized (faster, use in single-threaded test code). In parallel test generation, prefer StringBuilder per thread or StringBuffer if sharing one builder (rare).', e: 'Thread safety trade-off — StringBuilder for single-threaded tests.' },
  'Important String methods?': { a: 'Key methods: length(), charAt(), substring(), toLowerCase/toUpperCase(), trim(), replace(), split(), contains(), startsWith/endsWith(), indexOf(), equals/equalsIgnoreCase(), isEmpty/isBlank(), format(), join(). In automation: split CSV data, contains for soft assertions, trim for input cleanup.', e: 'Name 5-6 methods with automation use cases.' },
  'String concatenation performance?': { a: 'Using + in loops creates many intermediate String objects (O(n²) total copying). Compiler optimizes compile-time constants but not loop concatenation. Use StringBuilder.append() in loops building dynamic locators or SQL. For few concatenations, + is readable and fine.', e: 'Loop concatenation — StringBuilder mandatory.' },
  'How to reverse a String?': { a: 'StringBuilder sb = new StringBuilder(str); return sb.reverse().toString(); Or two-pointer char array swap. String has no reverse method. In interviews, mention immutability requires new object. Time O(n), space O(n).', e: 'StringBuilder reverse or two-pointer approach.' },
  'How to check palindrome?': { a: 'Two pointers at start and end, compare chars moving inward. Or reverse string and compare with equals(). Ignore case/non-alphanumeric for full variant. Time O(n). Common coding question — write clean loop, handle empty string edge case.', e: 'Two-pointer O(n) without extra space preferred.' },
  'String to char array?': { a: 'char[] chars = str.toCharArray(); creates copy of internal characters. Modify array without affecting original String (immutability). Reverse array in-place for palindrome check. Prefer toCharArray over manual charAt loop for clarity.', e: 'toCharArray() returns copy — String unchanged.' },
  'char array to String?': { a: 'new String(charArray) or String.valueOf(charArray). After in-place array manipulation, wrap back to String for assertions. String.copyValueOf(charArray, offset, count) for partial conversion.', e: 'valueOf and constructor both valid.' },
  'String.format usage?': { a: 'String.format("User %s logged in at %d", name, timestamp) or System.out.printf. Format specifiers: %s string, %d int, %f float, %n newline. Useful for dynamic log messages and test report templates: String.format("FAIL: %s expected [%s] but got [%s]", testName, expected, actual).', e: 'Format specifiers and logging/report use case.' },
  'String.join usage?': { a: 'String.join(", ", list) joins iterable with delimiter (Java 8). Cleaner than manual loop for CSV output or building tag strings. Arrays: String.join("-", "a","b","c"). Null delimiter throws NPE; elements can be null (prints "null").', e: 'Java 8 join — cleaner than StringBuilder for simple joins.' },
  'Split vs tokenizer?': { a: 'split(regex) returns String[] using regex (handles empty trailing strings differently). StringTokenizer legacy, not regex-based. Prefer split for CSV: line.split(",", -1) preserves trailing empties. split uses regex — escape dot: split("\\\\.").', e: 'split is modern; mention regex escaping.' },
  'Replace vs replaceAll?': { a: 'replace(old, new) literal string replacement. replaceAll(regex, replacement) uses regex — special chars need escape. replaceFirst replaces first match only. For dynamic IDs in locators, replace("{{id}}", actualId) is safer than replaceAll without regex intent.', e: 'Literal replace vs regex replaceAll.' },
  'Intern method?': { a: 'str.intern() returns pooled canonical reference. If pool has equal string, returns pool copy; else adds and returns. Rarely needed in test code. Useful for memory optimization with many duplicate literals. "hello".intern() == "hello" is true.', e: 'Returns canonical pool reference.' },
  'CompareTo vs equals?': { a: 'equals() returns boolean for equality. compareTo() returns int: negative/zero/positive for less/equal/greater (Comparable interface). Used for sorting. "b".compareTo("a") > 0. Strings compare lexicographically. sort() uses compareTo internally.', e: 'compareTo for ordering; equals for equality.' },
  'Empty vs null String?': { a: 'null means no object reference — NPE if you call methods. Empty string "" is valid object with length 0. Check null first: if (s != null && !s.isEmpty()). isBlank() (Java 11) treats whitespace-only as blank. Defensive checks in test data parsing prevent NPE.', e: 'Null check before isEmpty — classic NPE trap.' },
  'Best practices for String in tests?': { a: 'Use equals/equalsIgnoreCase for comparisons, never == for content. Use StringBuilder for dynamic building. Trim/normalize user input before assertion. Use formatted messages in Assert.fail(). Store locators as constants (final String). Avoid concatenating locators in loops without StringBuilder.', e: 'equals not ==; trim inputs; constants for locators.' },

  // ===== SCENARIO (50) - specific high-value =====
  'Flaky test due to timing — how do you fix?': { a: 'Replace Thread.sleep with explicit WebDriverWait and appropriate ExpectedCondition (visibility, clickable, invisibility of loader). Identify root cause: AJAX, animation, or race condition. Add stable locators (data-testid). Use polling with FluentWait for slow backends. Log wait timeouts with page URL for debugging. Never increase sleep — fix the condition.', e: 'Explicit waits + root cause analysis — never "just add more sleep".' },
  'Dynamic element ID changes every build — strategy?': { a: 'Avoid ID if dynamic. Use stable attributes: data-testid, name, aria-label. CSS partial match: [id^="user-"]. XPath contains(@id,"user"). Relative locators in Selenium 4. Partner with devs to add test-friendly attributes. Store locator strategy in page object for single-point update.', e: 'Stable attributes and dev collaboration — not brittle absolute XPath.' },
  'Test passes locally but fails in CI — debug approach?': { a: 'Compare: browser version, headless vs headed, screen resolution, timing (CI slower), test data, environment URL. Check CI logs, screenshots, video. Run CI Docker image locally. Verify parallel isolation (shared state?). Increase diagnostic logging in CI. Common causes: headless rendering differences, implicit wait conflicts, missing env vars.', e: 'Systematic environment diff — not "works on my machine" shrug.' },
  'Parallel execution causes test interference?': { a: 'Use ThreadLocal&lt;WebDriver&gt; so each thread has isolated driver. Avoid static mutable shared state. Unique test data per thread (UUID suffix). Separate browser profiles/downloads folders. Do not share same user account simultaneously. Reset app state or use independent test accounts.', e: 'ThreadLocal driver + isolated test data — mandatory for parallel.' },
  'How to reduce test execution time?': { a: 'Run parallel (TestNG parallel=methods/tests). Use headless browsers in CI. Remove unnecessary sleeps; optimize waits. Skip redundant setup via @BeforeClass smartly. API setup instead of UI where possible. Tag smoke vs full regression. Grid/Docker for scalable parallelism. Profile slow tests and fix top offenders.', e: 'Parallel + headless + API setup — quantified improvement if possible.' },
  'Version upgrade Selenium 3 to 4 — migration steps?': { a: 'Update Maven dependency to 4.x. Replace DesiredCapabilities with browser Options classes. Change timeout int seconds to Duration.ofSeconds(). Update JSON Wire deprecated APIs. Test W3C protocol compatibility. Leverage new features: relative locators, DevTools. Run full regression and fix deprecated method warnings.', e: 'Duration API and Options classes — concrete migration items.' },
  'Architecting framework for 50+ test engineers?': { a: 'Layered architecture: tests → page objects → utilities → core (driver, config). Modular Maven multi-module project. Strict coding standards and PR reviews. Central driver factory with ThreadLocal. CI pipeline with parallel Grid. Documentation portal, archetype project, office hours. Metrics dashboard for flakiness and coverage.', e: 'Scale through standards, modularity, and self-service documentation.' },

  // ===== JAVA COLLECTIONS (25) =====
  'List vs Set vs Map?': { a: 'List: ordered, allows duplicates, index access (ArrayList). Set: no duplicates, uniqueness checks (HashSet). Map: key-value pairs, unique keys (HashMap). Use List for test execution order; Set for unique browser types; Map for test data key-value lookup.', e: 'Purpose-driven selection with automation example each.' },
  'ArrayList internal working?': { a: 'Backed by dynamic Object array. Default capacity 10; grows ~1.5x when full (copy to new array). get(index) is O(1). Insert at end amortized O(1); middle insert O(n) due to shifting. Random access makes it ideal for indexed test data lists.', e: 'Dynamic array, growth factor, O(1) get.' },
  'LinkedList internal working?': { a: 'Doubly-linked nodes with prev/next pointers. Insert/delete at head/tail O(1). get(index) O(n) — traverse from nearest end. Implements List and Deque. Rarely best choice in automation; ArrayList usually faster for typical test data sizes.', e: 'Node structure; poor random access vs ArrayList.' },
  'ArrayList vs LinkedList?': { a: 'ArrayList: array-backed, fast get/set, slower middle insert. LinkedList: node chain, fast ends insert, slow random access. For test data under 10k items with frequent iteration, ArrayList wins due to cache locality. Use LinkedList only for queue/deque operations.', e: 'Default to ArrayList unless deque behavior needed.' },
  'HashSet internal working?': { a: 'HashMap backing — elements stored as keys with dummy PRESENT value. add() uses hashCode to bucket index, equals() for collision chain. No duplicates because keys must be unique. O(1) average add/contains. Use for unique test run IDs or deduplicating failure messages.', e: 'HashMap-backed; hashCode/equals contract critical.' },
  'TreeSet ordering?': { a: 'Red-black tree implementation of NavigableSet. Elements sorted by natural order (Comparable) or Comparator. O(log n) add/contains. No null if natural ordering. Use when you need sorted unique browser priority list or ordered test tags.', e: 'Sorted; O(log n); no null with natural order.' },
  'HashMap internal working?': { a: 'Array of buckets (default 16, load factor 0.75). hashCode() maps to bucket. Collision: linked list (tree if more than 8 nodes, Java 8+). get: hash, bucket, equals chain. Resize doubles buckets when threshold exceeded.', e: 'Whiteboard: hashCode, bucket, collision chain/tree.' },
  'HashMap collision handling?': { a: 'Same bucket: linked list of entries. Java 8+: list converts to red-black tree when length exceeds 8 (TREEIFY_THRESHOLD). Poor hashCode degrades to O(n). Keys must implement hashCode/equals consistently.', e: 'Chaining + treeification threshold in Java 8+.' },
  'LinkedHashMap use case?': { a: 'HashMap plus doubly-linked list maintaining insertion order (or access order). Slightly more memory. Use for LRU cache or preserving test config read order. Iteration order predictable unlike HashMap.', e: 'Insertion-order iteration — config or cache use case.' },
  'TreeMap use case?': { a: 'Red-black tree sorted by key. NavigableMap with subMap, floorKey. O(log n) operations. No null keys. Use when tests need environment priority map processed in sorted order.', e: 'Sorted keys; NavigableMap operations.' },
  'Hashtable vs HashMap?': { a: 'Hashtable: synchronized (thread-safe), legacy, no null keys/values. HashMap: not synchronized, allows one null key, faster. Use ConcurrentHashMap for thread-safe instead of Hashtable. Never use Hashtable in new code.', e: 'Hashtable legacy — ConcurrentHashMap for concurrency.' },
  'ConcurrentHashMap working?': { a: 'Java 8+: node arrays with synchronized bin heads or tree bins; CAS for lock-free reads. No null keys/values. Better throughput than Hashtable. Use for shared test result cache in parallel runs.', e: 'Fine-grained locking; no null; parallel-safe cache.' },
  'Iterator vs ListIterator?': { a: 'Iterator: forward only, all collections, can remove. ListIterator: bidirectional, List only, can add/set/replace. Fail-fast: ConcurrentModificationException if collection modified during iteration (except Iterator.remove).', e: 'Fail-fast and safe remove via Iterator.remove().' },
  'Fail-fast vs fail-safe?': { a: 'Fail-fast (ArrayList iterator): throws ConcurrentModificationException on concurrent modification. Fail-safe (CopyOnWriteArrayList iterator): iterates snapshot copy. In parallel test runners, fail-safe collections avoid CME but with memory cost.', e: 'CME on fail-fast; snapshot on fail-safe.' },
  'Comparable vs Comparator?': { a: 'Comparable: natural ordering via compareTo() implemented by class itself. Comparator: external comparison logic via compare(). Use Comparator.comparing(TestCase::getPriority) for flexible test sorting without modifying TestCase class.', e: 'Internal natural order vs external Comparator.' },
  'Collections.sort vs Arrays.sort?': { a: 'Collections.sort(list) sorts List. Arrays.sort(array) sorts array. Java 8+: list.sort(comparator) preferred. Both use TimSort O(n log n). Sort test cases by priority before execution.', e: 'list.sort() in Java 8+; TimSort underlying.' },
  'When to use which collection?': { a: 'ArrayList: default list. HashSet: uniqueness. HashMap: key-value lookup. LinkedHashMap: order matters. TreeMap/TreeSet: sorted. ConcurrentHashMap: parallel shared state. PriorityQueue: next test by priority.', e: 'Decision flowchart verbally — access, order, thread safety.' },
  'Map iteration techniques?': { a: 'entrySet() for key+value. keySet() for keys only. Java 8: map.forEach((k,v) -> ...). Stream: map.entrySet().stream(). Avoid iterating keySet then get() — entrySet is cleaner.', e: 'entrySet and forEach — not keySet + get loop.' },
  'Remove while iterating?': { a: 'Never use collection.remove() in enhanced for-loop — CME. Use Iterator.remove() after it.next(). Or removeIf (Java 8). Collect to new list via stream filter for immutable approach.', e: 'Iterator.remove() or removeIf — never foreach + remove.' },
  'Custom comparator example?': { a: 'Comparator byDuration = Comparator.comparingInt(TestResult::getDuration).reversed(); list.sort(byDuration); Chain: comparing().thenComparing(). Null-safe: nullsLast(naturalOrder()).', e: 'Method reference comparator with thenComparing chain.' },
  'Queue and Deque?': { a: 'Queue: FIFO — LinkedList or ArrayDeque. Deque: double-ended. ArrayDeque faster than LinkedList for queue. Use Queue for test job scheduling in custom parallel runner.', e: 'ArrayDeque preferred over LinkedList for queue.' },
  'PriorityQueue?': { a: 'Heap-based priority queue — head is least element per natural order or Comparator. O(log n) insert/remove. Not thread-safe. Schedule tests by priority with custom Comparator.', e: 'Heap structure; custom priority ordering.' },
  'CopyOnWriteArrayList?': { a: 'Thread-safe List — every write copies entire array. Iterators never throw CME. Expensive writes, fast reads. Use when reads vastly outnumber writes — listener list in test event bus.', e: 'Snapshot iteration; write-heavy cost.' },
  'WeakHashMap?': { a: 'Keys held by weak references — eligible for GC when no strong refs. Entries auto-removed on GC. Use for caches that should not prevent GC. Rare in test code; shows advanced collection knowledge.', e: 'Weak references for GC-friendly cache.' },
  'EnumSet and EnumMap?': { a: 'Specialized Set/Map for enum keys — compact and very fast. Use EnumMap for type-safe browser registry in driver factory.', e: 'Type-safe enum-keyed collections — driver factory example.' },

  // ===== JAVA EXCEPTIONS (15) =====
  'Checked vs unchecked exception?': { a: 'Checked (IOException): compiler forces handle or declare throws. Unchecked (RuntimeException, NPE): optional handling. Use checked for recoverable external failures; unchecked for programming errors.', e: 'Compile-time enforcement for checked only.' },
  'try-catch-finally flow?': { a: 'try executes; catch handles matching exception; finally always runs (except System.exit or fatal error). If return in try, finally still runs before return. Use try-with-resources instead of finally for closing streams.', e: 'Finally always runs; prefer try-with-resources.' },
  'Can finally block be skipped?': { a: 'Yes: System.exit(), JVM crash, infinite loop in try, or thread death. If return in try and return in finally, finally wins. Do not put return in finally — bad practice.', e: 'System.exit and fatal errors skip finally.' },
  'Custom exception creation?': { a: 'Extend Exception (checked) or RuntimeException (unchecked). Provide constructors with message and cause. Use for domain errors: ElementNotFoundInPageException extends RuntimeException.', e: 'Meaningful name + message + cause constructor.' },
  'throw vs throws?': { a: 'throw: statement to raise exception instance. throws: method signature declares checked exceptions caller must handle. throw is action; throws is declaration.', e: 'throw raises; throws declares — different roles.' },
  'Exception vs Error?': { a: 'Exception: recoverable conditions (IOException). Error: serious JVM problems (OutOfMemoryError) — do not catch. Catch Exception in framework top-level handler; never swallow Error.', e: 'Do not catch Error — JVM-level failures.' },
  'Multi-catch block?': { a: 'catch (IOException | SQLException e) handles multiple types in one block (Java 7+). e is effectively final. Cannot catch subclass and superclass together.', e: 'Pipe-separated types; single handler block.' },
  'try-with-resources?': { a: 'try (FileReader fr = new FileReader(f)) auto-closes AutoCloseable resources in reverse order. Suppressed exceptions preserved. WebDriver is not AutoCloseable — use quit() in @AfterMethod.', e: 'AutoCloseable and suppressed exception handling.' },
  'Best practices for exceptions?': { a: 'Catch specific types, not Exception. Log with context (test name, URL). Never empty catch. Use custom exceptions for framework errors. Fail fast with clear messages.', e: 'Specific catch, log context, never swallow.' },
  'Exception handling in framework?': { a: 'ITestListener.onTestFailure captures exception, screenshot, logs. BaseTest wraps actions with try-catch for soft asserts. Retry only on known transient exceptions (StaleElementReferenceException).', e: 'Listener integration and contextual logging.' },
  'Logging exceptions?': { a: 'logger.error("Test {} failed on page {}", testName, url, e) — pass throwable as last arg for stack trace. Use SLF4J/Log4j2 levels appropriately.', e: 'Parameterized logging with exception as last parameter.' },
  'Suppressed exceptions?': { a: 'When try-with-resources close() throws while try block also threw, close exception is suppressed on primary. getSuppressed() retrieves them.', e: 'try-with-resources multi-exception scenario.' },
  'RuntimeException examples?': { a: 'NullPointerException, IllegalArgumentException, IllegalStateException, IndexOutOfBoundsException, ClassCastException. Indicate programming bugs. Validate inputs early: Objects.requireNonNull(driver).', e: 'Name 3-4 common unchecked exceptions.' },
  'When not to catch Exception?': { a: 'Do not catch broad Exception unless rethrowing or top-level framework handler. Catching Exception hides bugs. Catch specific Selenium exceptions with targeted recovery.', e: 'Avoid catch(Exception e) empty blocks.' },
  'Global exception handler pattern?': { a: 'UncaughtExceptionHandler for threads in parallel runs. TestNG ITestListener for test-level. Central ErrorHandler that logs, screenshots, and categorizes failures for reporting.', e: 'Central handler with screenshot + categorization.' },

  // ===== JAVA 8 (20) =====
  'What is a lambda expression?': { a: 'Anonymous function: (parameters) -> expression or { statements }. Requires functional interface target. Replaces verbose anonymous inner classes in test utilities.', e: 'Syntax and functional interface requirement.' },
  'Functional interface types?': { a: 'Predicate (test), Function (transform), Consumer (accept), Supplier (supply). java.util.function package. Custom: @FunctionalInterface interface TestValidator { boolean validate(WebDriver d); }', e: 'Name Predicate, Function, Consumer, Supplier with roles.' },
  'Predicate example?': { a: 'Predicate isEnabled = el -> el.isEnabled(); list.stream().filter(isEnabled).forEach(el -> el.click()); Combine: isEnabled.and(isDisplayed).', e: 'filter() with Predicate in stream pipeline.' },
  'Function example?': { a: 'Function toLocator = id -> By.id(id); Transform test data strings to locators. Used with map() in stream pipelines.', e: 'map() transforms T to R.' },
  'Consumer example?': { a: 'Consumer highlight = el -> js.executeScript("arguments[0].style.border=\'3px solid red\'", el); elements.forEach(highlight); Side effect without return value.', e: 'forEach accepts Consumer — side effect operation.' },
  'Supplier example?': { a: 'Supplier driverSupplier = () -> new ChromeDriver(); Lazy initialization with orElseGet(driverSupplier). Defers expensive creation until needed.', e: 'orElseGet with Supplier for lazy creation.' },
  'Stream intermediate vs terminal?': { a: 'Intermediate (filter, map, sorted) return Stream — lazy, not executed. Terminal (collect, forEach, count) trigger processing. Nothing runs until terminal operation.', e: 'Lazy intermediate; terminal triggers execution.' },
  'map vs flatMap?': { a: 'map: one-to-one transform. flatMap: one-to-many flatten — flattens nested streams. Get all links: pages.stream().flatMap(p -> p.getLinks().stream()).', e: 'flatMap flattens nested structures.' },
  'filter operation?': { a: 'Stream.filter(Predicate) keeps elements matching condition. Example: testResults.stream().filter(r -> r.isFailed()).count().', e: 'Predicate-based selection in pipeline.' },
  'reduce operation?': { a: 'Terminal: stream.reduce(identity, accumulator). Or mapToInt(TestResult::getDuration).sum() for primitives.', e: 'Accumulator pattern or specialized sum/count.' },
  'collect vs collect(Collectors)?': { a: 'collect(Collector) gathers stream to collection. Collectors.toList(), toSet(), toMap(), groupingBy(), joining(). Group tests by suite for report dashboard.', e: 'groupingBy and toMap are interview favorites.' },
  'Optional best practices?': { a: 'Use for return types only, not fields/parameters. Avoid get() without check — use orElse, orElseGet, orElseThrow. Chain: findUser(id).map(User::getEmail).orElse("unknown").', e: 'Return type only; orElseGet over get().' },
  'Method reference types?': { a: 'Static: ClassName::staticMethod. Instance: instance::method. Arbitrary: WebElement::click. Constructor: ArrayList::new. list.forEach(System.out::println).', e: 'Four types — static, bound, unbound, constructor.' },
  'Parallel streams?': { a: 'parallelStream() uses ForkJoinPool.commonPool(). Good for CPU-heavy pure operations. Bad for I/O (WebDriver calls) — not thread-safe. Never parallelStream on shared WebDriver operations.', e: 'CPU-bound only — never for WebDriver I/O.' },
  'Date/Time API (LocalDate)?': { a: 'java.time: LocalDate, LocalDateTime — immutable, thread-safe. Replace legacy Date/Calendar. Parse and format with DateTimeFormatter for date picker test data.', e: 'Immutable java.time vs legacy Date.' },
  'Default methods in interface?': { a: 'Java 8: interface can have default method with body. Implementing class inherits default unless overridden. Enables interface evolution without breaking implementers.', e: 'Backward-compatible interface extension.' },
  'Static methods in interface?': { a: 'Java 8: interface static methods called via InterfaceName.method(). Not inherited. Utility methods on interface definition.', e: 'Called on interface, not inherited.' },
  'Stream vs Collection?': { a: 'Collection stores elements; Stream computes pipeline over source. Stream is consumable — one use only. Use stream for filter/map/reduce; collection for persistent storage.', e: 'Stream is pipeline; collection is data store.' },
  'peek operation?': { a: 'Intermediate: stream.peek(Consumer) performs side effect (debug log) without changing elements. Use sparingly — prefer proper logging in forEach.', e: 'Debug side effect — not for production logic.' },
  'groupingBy collector?': { a: 'Collectors.groupingBy(classifier) returns Map of grouped lists. groupingBy(Test::getStatus, counting()) for counts. Group failed tests by error type for report.', e: 'Classifier + optional downstream collector.' },

  // ===== JAVA MULTITHREADING (15) =====
  'Thread vs Runnable?': { a: 'Thread is a class — extend and override run(). Runnable is interface — implement run(), pass to new Thread(runnable).start(). Prefer Runnable (composition) over extending Thread.', e: 'Prefer Runnable — avoids single inheritance waste.' },
  'start() vs run()?': { a: 'start() creates new thread and calls run() asynchronously. Calling run() directly executes in current thread — no parallelism. Always start() for new thread.', e: 'start() = new thread; run() = synchronous call.' },
  'Thread lifecycle?': { a: 'States: NEW, RUNNABLE, BLOCKED/WAITING/TIMED_WAITING, TERMINATED. start() moves NEW to RUNNABLE. Monitor thread dumps in hung Grid node debugging.', e: 'Name states: NEW, RUNNABLE, WAITING, TERMINATED.' },
  'synchronized keyword?': { a: 'Synchronized method or block ensures mutual exclusion — one thread at a time. In tests, prefer ThreadLocal driver over synchronized. Over-synchronization hurts parallel performance.', e: 'Mutual exclusion; prefer ThreadLocal over sync in tests.' },
  'volatile keyword?': { a: 'Volatile ensures visibility — writes visible to all threads immediately. No atomicity for compound ops. Use for simple flags: volatile boolean stopRequested.', e: 'Visibility guarantee — not atomic compound operations.' },
  'ThreadLocal usage?': { a: 'ThreadLocal gives each thread its own WebDriver instance. driver.set(new ChromeDriver()); driver.get(); driver.remove() in @AfterMethod prevents leaks. Core pattern for parallel Selenium.', e: 'WebDriver ThreadLocal — must-know for senior roles.' },
  'Deadlock — what and prevention?': { a: 'Two threads hold locks other needs — circular wait. Prevention: lock ordering, timeout (tryLock), avoid nested locks. Shared test accounts in Grid can mimic deadlock symptoms.', e: 'Lock ordering and tryLock prevention strategies.' },
  'wait vs sleep?': { a: 'wait(): Object method, releases lock, must be in synchronized block. sleep(): Thread static, does not release lock. Never use Thread.sleep in Selenium — use WebDriverWait.', e: 'wait releases lock; sleep does not — neither for Selenium waits.' },
  'notify vs notifyAll?': { a: 'notify() wakes one waiting thread. notifyAll() wakes all. Called from synchronized block. Prefer java.util.concurrent over manual wait/notify.', e: 'One vs all; prefer concurrent utilities.' },
  'ExecutorService?': { a: 'Thread pool manager: Executors.newFixedThreadPool(4). submit(Callable) returns Future. shutdown() graceful stop. Use for custom parallel test runner.', e: 'Thread pool vs manual Thread per task.' },
  'Callable vs Runnable?': { a: 'Runnable: void run(), no return. Callable: V call() returns value, throws Exception. Future result = executor.submit(callable); result.get() blocks.', e: 'Callable returns value and throws checked exceptions.' },
  'Future interface?': { a: 'Represents async computation result. get() blocks until complete. isDone(), cancel(mayInterrupt). CompletableFuture supports chaining thenApply.', e: 'get() blocks; CompletableFuture for chaining.' },
  'CountDownLatch?': { a: 'One-shot latch — countDown() decrements; await() blocks until zero. Coordinate parallel test setup before execution starts.', e: 'One-time coordination — setup synchronization.' },
  'CyclicBarrier?': { a: 'Reusable barrier — threads await at barrier point, all proceed when count reached. Use when N parallel tests must sync before next phase.', e: 'Reusable multi-thread rendezvous point.' },
  'Thread safety in HashMap?': { a: 'HashMap is not thread-safe — concurrent put/get may corrupt structure. Use ConcurrentHashMap for shared maps in parallel tests.', e: 'Never share HashMap across threads — use CHM.' },

  // ===== SELENIUM KEY =====
  'What is Selenium?': { a: 'Open-source suite for browser automation. WebDriver drives browsers natively; Grid enables distributed execution. Supports Java, Python, C#. Industry standard for functional web UI testing.', e: 'Suite overview — WebDriver + Grid + multi-language.' },
  'Selenium components?': { a: 'Selenium IDE (record/playback), WebDriver (API + browser drivers), Grid (hub/node distributed execution). WebDriver is primary for robust frameworks.', e: 'WebDriver vs IDE vs Grid roles.' },
  'Selenium architecture?': { a: 'Test code to WebDriver API to Browser Driver (ChromeDriver) to Browser. Selenium 4 uses W3C WebDriver protocol. Driver acts as proxy translating commands.', e: 'Client to driver to browser chain; W3C protocol.' },
  'WebDriver interface?': { a: 'Core interface: get(), findElement(), getTitle(), quit(), manage(), navigate(). Implemented by ChromeDriver, FirefoxDriver. Code against WebDriver for cross-browser portability.', e: 'Program to interface — factory for browser swap.' },
  'Selenium 3 vs 4?': { a: 'Selenium 4: W3C protocol, relative locators, Chrome DevTools, improved Grid, Duration-based timeouts, newWindow API. Migration: Options classes replace DesiredCapabilities.', e: 'W3C, relative locators, DevTools, Grid 4.' },
  'Implicit vs explicit wait?': { a: 'Implicit: global timeout on findElement. Explicit: condition-based wait for specific element state. Never mix both — unpredictable total wait. Use explicit only in mature frameworks.', e: 'Never mix — explicit preferred for precision.' },
  'What is Page Object Model?': { a: 'Design pattern: each page is a class with locators and methods. Tests call page.login(user, pass) not raw findElement. Reduces duplication, centralizes locator changes.', e: 'Encapsulation of locators and page actions.' },
  'What is Selenium Grid?': { a: 'Distributed execution: Hub routes tests to Node with matching browser/OS. Enables parallel cross-browser testing at scale. Grid 4 supports Docker deployment.', e: 'Hub-node architecture and parallel cross-browser.' },
  'close() vs quit()?': { a: 'close(): closes current window/tab; session may remain. quit(): closes all windows and terminates WebDriver session. Always quit() in @AfterMethod. close() alone causes session leaks in Grid.', e: 'quit() in teardown — always; close() is partial.' },
  'StaleElementReferenceException?': { a: 'Element found but DOM refreshed — reference invalid. Fix: re-find element after page update. Use explicit wait for stability. Page Factory @FindBy re-locates on access.', e: 'Re-find after DOM change; Page Factory lazy init.' },
  'findElement vs findElements?': { a: 'findElement: returns first match or throws NoSuchElementException. findElements: returns empty List if none — never throws for missing elements. Use findElements to check existence without exception.', e: 'Exception vs empty list — existence check pattern.' },
  'Why not Thread.sleep()?': { a: 'Fixed delay wastes time or still fails if delay insufficient. Non-responsive to actual page state. Use WebDriverWait with ExpectedConditions for condition-based synchronization. sleep masks real timing bugs.', e: 'Explicit waits — never sleep in production framework.' },
  'CSS vs XPath when?': { a: 'CSS: faster engine, readable, good for id/class/attribute. XPath: text matching, axes traversal, parent navigation, complex conditions. Prefer CSS; XPath when CSS cannot express the locator.', e: 'CSS default; XPath for text and axes.' },
  'POM vs Page Factory?': { a: 'POM: manual By locators in page class. Page Factory: @FindBy annotations + PageFactory.initElements for lazy element proxy initialization. Page Factory reduces boilerplate but same design pattern.', e: 'Page Factory is POM implementation technique.' },
};

module.exports = { getQA, ANSWERS };
